### PR TITLE
Complies with rfc7231 about statuses 307 and 308

### PR DESCRIPTION
**Pull request by vkravets**
Fix for #2874 #3111 and #4229

### CODE REVIEW

**Comment by swankjesse** [comment]
This is a straightforward change with very dramatic consequences. I’m agree that we should do this, but should be very cautious when rolling it out. 

One option is to give users a sample network interceptor that restores the previous behavior. It would probably just strip the Location header or something to prevent the redirect.

**Comment by vkravets** [comment]
I'm not sure that intercepter will good idea for that... I want to propose solution with flag in the same way what is done for redirects, by default it will be false and old behavior will be working.... Otherwise new behavior of redirection for 307 and 308 will be used.

Main question how name such flag...
1. `setFollowAutomaticRedirect()` and `isFollowAutomaticRedirect()`
2. also we can check system variable, default behavior - old, if system variable specified - use new behavior...

As for me example of intercepter will more confuse end user instead of set the understanding of what this intercepter performs.

**Comment by yschimke** [comment]
@swankjesse I don't like optional network interceptors if we think there is a better default.  Most users won't know to add the interceptor.  Should we just make the change as an opinionated user agent and have a way to disable to previous behaviour?

**Comment by swankjesse** [comment]
Let's fix this and offer an interceptor to restore the previous behavior.

**Comment by yschimke** [comment]
I'll take a look at the alternate fix unless @vkravets is interested in making the changes?

**Comment by yschimke** [comment]
Realised since I intended to migrate the changes to Kotlin, it's worth keeping this open for now.

**Comment by yschimke** [comment]
I'll take a look at this hopefully in next week.

**Comment by yschimke** [comment]
@swankjesse How do you make big changes on a PR like this while retaining the author?

**Comment by swankjesse** [comment]
@yschimke either `commit --amend` or use the git commit option that takes author metadata.

**Comment by CoryARamirez** [comment]
@swankjesse is there an ETA as to when this will be complete?

**Comment by swankjesse** [comment]
🔜

**Comment by yschimke** [comment]
Also possibly relevant https://github.com/square/okhttp/issues/3111

**Comment by yschimke** [comment]
Migrated current logic to kotlin in https://github.com/square/okhttp/pull/5990, with author retained

**Pull request closed without merging**
