### PR TITLE
Code quality fix - Strings literals should be placed on the left side when checking for equality

### PR DESCRIPTION
**Pull request by AhmedDaraz**
This pull request is focused on resolving occurrences of Sonar rule squid:S1132 - “Strings literals should be placed on the left side when checking for equality”. You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1132

Please let me know if you have any questions.

Ahmed Daraz

### CODE REVIEW

**Comment by swankjesse** [comment]
Please stop.

**Comment by swankjesse** [comment]
(These rules are misguided, and they make the code worse.)

**Comment by iNoles** [comment]
Only reason for this is avoid NPE. I do see potential NPE on JavaApiConverter.java for fieldValues == null by Line 179.

**Comment by JakeWharton** [comment]
`fieldValues` is never dereferenced in that code path.

**Pull request closed without merging**
