### PR TITLE
Release the connection when an Authenticator throws an exception.

### PR DESCRIPTION
**Pull request by dave-r12**
Closes: https://github.com/square/okhttp/issues/3872

### CODE REVIEW

**Comment by dave-r12** [comment]
I stoles the changes from https://github.com/square/okhttp/pull/3885 ... and added some tests!

**Comment by yschimke** [comment]
hmmm.... from https://github.com/square/okhttp/pull/3971/commits I thought this would keep the original author.  Not sure it did, was that because of squash merge?

**Comment by swankjesse** [comment]
LGTM

**Comment by dave-r12** [comment]
Ahh, yeah I tried to retain the original author. My bad.

**Pull request merged**
