### PR TITLE
Fix a bug where responses weren't closed on a late cancel (3.12.x branch)

### PR DESCRIPTION
**Pull request by swankjesse**
Closes: https://github.com/square/okhttp/issues/4583

### CODE REVIEW

**Comment by Tolriq** [comment]
@swankjesse @yschimke  Beware that this way of fixing the issue is a breaking change. (Including the merged one for 3.14)

It's still totally possible to have another thread that cancels at https://github.com/square/okhttp/blob/bf394560e1c83d05a552079634359fad9e0a640b/okhttp/src/main/java/okhttp3/RealCall.java#L202 point.

Before it would have thrown, call failure and leaked the response, now it will call onResponse (so success) and ignore the cancel.

Personally I'm fine with the change as I find better to have a success call than a leak but I'm not sure this was wanted with that version of the fix.

**Comment by swankjesse** [comment]
Needs to be rebased on this:
https://github.com/square/okhttp/pull/4652

**Comment by swankjesse** [comment]
@Tolriq yep! You can also cancel a call while it’s being processed in `onResponse()`. When this happens the response body stream will throw an IOException, but the `onResponse()` implementation is still responsible for closing it.

**Comment by Tolriq** [comment]
@swankjesse Yes I know and handle all the cases and found this issue, just pointing that the way of fixing it is a breaking change in some user cases. 
A late cancel would have called onFailure now it can call onReponse.

If a user expect that onResponse is not called for cancelled calls this is breaking change and may require proper warning in the changelog that now a check for call.isCanceled() might be wanted in the onResponse callback due to this change since it can now happens.

**Comment by Tolriq** [comment]
Just a side note that changelog does not contains a comment about the fact that a cancelled call can reach onResponse now after those fixes. (3.14 and 3.12.x)

**Comment by swankjesse** [comment]
@Tolriq it was already possible previously. The call is often canceled while reading the response body.

**Comment by Tolriq** [comment]
@swankjesse I guess I badly explained in all previous comments so :)

The breaking change is that onResponse can be called with a call that is already cancelled. This was not possible before.
This change behaviors for API consumers, not all consumers want to actually use the body and will see an error if there's an error when using a body from a cancelled but successful call (I don't think so). And can start job / stuff that they are not supposed to do if the call was cancelled and never reached onResponse.

Furthermore the documentation says:
/** Cancels the request, if possible. Requests that are already complete cannot be canceled. */

So if onResponse is called a call.cancel() is said to do nothing. 

Now onResponse can be called with a call that is already cancelled and the consumer should not use the response, yet 99% of users certainly don't do call.isCancelled() check at the start of this function since it was not possible that is happened before.

Hope it's more clear why it's a breaking change and people should be aware, the race condition is now move to end user code.

**Comment by swankjesse** [comment]
There’s no ordering guarantees between cancel() and onResponse(), and a call can be canceled immediately after an isCanceled() check returns false.

**Comment by swankjesse** [comment]
Does this clarify? A call isn’t complete until the response body is exhausted or closed, which is also independent of when onResponse() is invoked.

**Comment by Tolriq** [comment]
Then docs are not clear enough about what complete is.

And this also means that it's virtually impossible to prevent the leaks in coroutines world so :(

```
return suspendCancellableCoroutine { continuation ->
            continuation.invokeOnCancellation {
                cancel()
            }
            enqueue(object : Callback {
                override fun onResponse(call: Call, response: Response) {
                    continuation.resume(WorkerResult.Success(response))
                }

                override fun onFailure(call: Call, e: IOException) {
                    if (call.isCanceled || !isActive) {
                        continuation.resume(WorkerResult.Error(CancellationException("Cancelled")))
                    } else {
                        continuation.resume(WorkerResult.Error(e))
                    }
                }
            })
        }
```

Can leak for example  coroutines 1.1.x ignores the resume when the call is cancelled and now with the race on client side the response is not closed :(
Maybe @JakeWharton have more idea about how to manage those races as retrofit coroutines will face that too.
Adding the isActive isCancelled check can face the race condition in onResponse,

**Comment by JakeWharton** [comment]
Retrofit doesn't have this problem because it doesn't propagate an open
resource. Seems like any coroutine that resumes with a resource will have
this problem. Is there anything specific to OkHttp?

**Comment by swankjesse** [comment]
Can you register a different cancelation handler in `onResponse()` ?

**Comment by Tolriq** [comment]
@JakeWharton you do the exact same thing:
https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/KotlinExtensions.kt#L69
and
https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/KotlinExtensions.kt#L89

Don't know how those extensions method are used currently but they present the same issue :(

@swankjesse not sure to understand your question :(

**Comment by JakeWharton** [comment]
Those aren't resources. They don't need closed. They're values.

**Comment by Tolriq** [comment]
Oh sorry, long time not used Retrofit, did not notice the Call is the same interface but not same API :(.

Will move this to coroutines support so.

**Comment by Tolriq** [comment]
See https://github.com/Kotlin/kotlinx.coroutines/issues/1044 for the coroutine part and design thinking by Roman Elizarov, maybe you have ideas to share :)

**Pull request merged**
