### PR TITLE
Fix snapshots link

### PR DESCRIPTION
**Pull request by PromanSEW**

### CODE REVIEW

**Comment by JakeWharton** [comment]
Hmm the problem is that the original URL is what you need to use for a build system

**Comment by PromanSEW** [comment]
@JakeWharton this link is not for browser navigation?
If not, it will be good to provide it as URL, not link

**Comment by JakeWharton** [comment]
No. It's for build systems.

**Comment by swankjesse** [comment]
Yeah, we don’t want people downloading these manually; that’s always going to spell trouble.

**Comment by swankjesse** [comment]
Thanks though!

**Comment by PromanSEW** [comment]
If you don't want that users download JARs manually, why you decorated this URL as link instead of plain text? -_-
I don't understand

**Pull request closed without merging**
