### PR TITLE
Evict connection pool a second time after tests

### PR DESCRIPTION
**Pull request by yschimke**
Debugging flakyness introduced in https://github.com/square/okhttp/pull/7815

### CODE REVIEW

**Comment by yschimke** [comment]
@swankjesse is iterating over the connections and calls safe here?

I think the fix to evict a second time after waiting 500ms extra, is the real fix.

**Comment by yschimke** [comment]
I'm hopeful this fixes about 50% of our flakes, ones of this form.

```
EventSourceHttpTest > cancelInEventShortCircuits() > okhttp3.sse.internal.EventSourceHttpTest.cancelInEventShortCircuits()[1] FAILED
    org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
        at okhttp3.OkHttpClientTestRule.ensureAllConnectionsReleased(OkHttpClientTestRule.kt:193)
```

**Comment by yschimke** [comment]
@swankjesse requesting post review

**Review by swankjesse — COMMENTED** [review]
LGTM

**Pull request merged**
