### PR TITLE
update maven plugins and apache.httpcomponents/httpclient to 4.2.6

### PR DESCRIPTION
**Pull request by based2**
http://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient

### CODE REVIEW

**Comment by JakeWharton** [comment]
Reminder that mvnrepository is a third party index and not canonical for maven central. search.maven.org is where maven central lives.

**Comment by based2** [comment]
https://archive.apache.org/dist/httpcomponents/httpclient/RELEASE_NOTES-4.5.x.txt

Release 4.2.3 -> ok, no 4.2.6
-------------------

HttpClient 4.2.3 (GA) is a bug fix release that addresses a number of issues reported since
release 4.2.2. This release also includes a thoroughly reworked NTLM authentication engine
which should result in a better compatibility with the newest Microsoft products.

Users of HttpClient 4.x are advised to upgrade.

**Comment by yschimke** [comment]
The timezone bug raised by the new version of error prone seems practically unlikely but technically legit.  Only in a test thankfully.

```
[ERROR] /home/travis/build/square/okhttp/okhttp-urlconnection/src/test/java/okhttp3/UrlConnectionCacheTest.java:[1082,48] [InvalidTimeZoneID] Invalid time zone identifier. TimeZone.getTimeZone(String) will silently return GMT instead of the time zone you intended.
[ERROR]     (see http://errorprone.info/bugpattern/InvalidTimeZoneID)
```

**Comment by swankjesse** [comment]
Thanks! Merged manually!

**Pull request merged**
