### PR TITLE
Better exception logging when exhausting routes

### PR DESCRIPTION
**Pull request by yschimke**

### CODE REVIEW

**Review by swankjesse — APPROVED** [review]
Thanks!

**Comment by swankjesse** [comment]
Hmmmm... It is empty. I don't like the ‘exhausted all routes’ error because it has less information than the failure message of any particular route. I wonder where we’re throwing that away?

**Comment by yschimke** [comment]
Agreed, but it looks like it has never had suppressed errors since it first got added.  Probably worth adding.

**Comment by yschimke** [comment]
Making this PR about adding those suppression in.

**Comment by yschimke** [comment]
@swankjesse This one is hurting in CI.  It seems like we get "exhausted all routes" when we get a connection, but health checks fails. Probably the SSL connection fails after we think we've connected.  

But there isn't an easy way to get an exception from this.

I suggest removing that check for now.  We already chain suppressed exceptions in the RouteException, but this isn't the same error flow.  So it can never pass.

```
    } catch (IOException expected) {
      assertThat(expected.getMessage()).isEqualTo("exhausted all routes");
      assertThat(expected.getSuppressed()).isNotEmpty();
    }
``` 

```

      // Confirm that the connection is good.
      if (candidate.isHealthy(doExtensiveHealthChecks)) {
        return candidate
      }

      // If it isn't, take it out of the pool.
      candidate.noNewExchanges()

      // Make sure we have some routes left to try. One example where we may exhaust all the routes
      // would happen if we made a new connection and it immediately is detected as unhealthy.
      if (nextRouteToTry != null) continue

      val routesLeft = routeSelection?.hasNext() ?: true
      if (routesLeft) continue

      val routesSelectionLeft = routeSelector?.hasNext() ?: true
      if (routesSelectionLeft) continue

      throw IOException("exhausted all routes")
```

**Comment by yschimke** [comment]
If we want to keep this, then we can record each IOException in RealConnection at the point we call listener.connectionFailed(), and also record that we have an unhealthy connection (the server closed the connection on us).

**Comment by swankjesse** [comment]
Works for me.

**Comment by swankjesse** [comment]
(Removing the check works for me. Improving the exception is a separate task that we can do later.)

**Comment by maldito-dot** [comment]
> https://github.com/top-gg/docs/tree/master/content%2Fapi%2Fbot.mdx

@maldito-dot

**Review by maldito-dot — COMMENTED** [review]
@monstro805

**Review by maldito-dot — COMMENTED** [review]
@maldito-dot

**Comment by yschimke** [comment]
No longer relevant

**Pull request closed without merging**
