### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bigman212**
Added link to Maven repo to simplify search for latest version number.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Even if we wanted to link, search.maven.org is the correct place. mvnrepository is a third-party index that's frequently out-of-date and shouldn't be used.

**Comment by bigman212** [comment]
> Even if we wanted to link, search.maven.org is the correct place. mvnrepository is a third-party index that's frequently out-of-date and shouldn't be used.

Oops, sorry for that, my mistake.
Should "same version as OkHttp dependency" recommendation go to readme.md then? How people, for example, that, are using retrofit should check OkHttp version?

**Comment by swankjesse** [comment]
If you’re using the logging interceptor, you should explicitly specify it’s version and the OkHttp version.

**Comment by bigman212** [comment]
Okay. What should i do next then with this PR?

**Comment by swankjesse** [comment]
Change the doc to recommend using the same version as your OkHttp artifact? Mind changing our other optional modules also?

**Comment by swankjesse** [comment]
Fixed our tools so the latest version is easy.
https://github.com/square/okhttp/pull/5129

**Pull request closed without merging**
