### PR TITLE
Inject a leading . for better matching under JavaNetCookieJar

### PR DESCRIPTION
**Pull request by swankjesse**
Closes: https://github.com/square/okhttp/issues/2549

### CODE REVIEW

**Comment by JakeWharton** [comment]
lgtm

**Comment by sisel** [comment]
LGTM,
seems it's not released yet , look forward to next release.

**Comment by michaelzengke** [comment]
So, this change suddenly reverts from always RFC 6265 to always RFC 2965. 

However, Cookie#parseDomain(String) always removes the leading ".", meaning Cookie impl chooses RFC 6265.

Are they contradicting each other?

Looks like either Cookie#parseDomain(String) should be agnostic to the upstream's RFC compliance, or CookieJar#saveFromResponse(HttpUrl, List<Cookie>) should be CookieJar#saveFromResponse(HttpUrl, List<String>) such that CookieJar impl can have its own choice of RFC compliance.

**Comment by swankjesse** [comment]
Here’s how I think of it:
 * All of OkHttp prefers RFC 6265 and uses that.
 * All of java.net prefers RFC 2965 and uses that.

The `JavaNetCookieJar` class is a bridge from OkHttp to java.net, so it formats cookies as RFC 2965 wants ’em. I’d like to also [someday](https://github.com/square/okhttp/issues/2890) make a `RealCookieJar` or something that doesn’t delegate to obsolete code in java.net.

**Comment by raskasa** [comment]
@swankjesse Should your explanation be added to the class-level Javadoc for, or as a code comment within, `JavaNetCookieJar`?

**Comment by michaelzengke** [comment]
I get your point. The problem here is, within our server farm, some cookies are issued per RFC 2965, some per RFC 6265. Our apps out in the market won't survive if okhttp3 modifies the domain in any way, add or remove the leading ".".

After all, CookieJar is designed such that users can choose various cookie handling strategy, isn't it?

If the interface is designed as CookieJar#saveFromResponse(HttpUrl, List), the choice is in the user's hands. Otherwise, today, when Cookie is passed down, whether the original domain has or has not the leading "." is no longer known to the user.

**Comment by swankjesse** [comment]
You probably want to fix your server to use RFC 6265 exclusively. RFC 2965 is a dead-end spec that was never widely deployed and isn’t well supported by browsers.

**Pull request merged**
