### PR TITLE
Enable GitHub Code Scanning

### PR DESCRIPTION
**Pull request by ddz**
Created a `codeql-analysis.yml` to configure GitHub workflow for code scanning.
* Added Setup Java action to override default Java 8.
* Added custom build command from CircleCI yml commented out in case CodeQL autobuild fails in the future.

### CODE REVIEW

**Review by swankjesse — APPROVED** [review]

**Comment by yschimke** [comment]
Is this posting to here?  Does this support kotlin?

https://lgtm.com/projects/g/square/okhttp/?mode=list
https://lgtm.com/query/project:7870357/lang:java/

**Comment by swankjesse** [comment]
Perhaps this doesn't help with .kt files?
https://help.semmle.com/codeql/supported-languages-and-frameworks.html

**Comment by ddz** [comment]
Yes, doesn't look like Kotlin is supported yet, but [it appears to be on their radar](https://news.ycombinator.com/item?id=24648281). So this scanning will only cover samples, mockwebserver, and some test code until then. It's definitely debatable whether it's worth the additional CI time until then.

**Comment by yschimke** [comment]
> It's definitely debatable whether it's worth the additional CI time until then.

Seems like a good initiative to support and will be nice when it becomes active.

**Pull request merged**
