### PR TITLE
Add maven bom

### PR DESCRIPTION
**Pull request by eddumelendez**
See gh-4329

### CODE REVIEW

**Comment by swankjesse** [comment]
Links to other projects adopting this? I'd like to compare!

**Comment by eddumelendez** [comment]
@swankjesse below you can few just some of the most important projects providing BOM

jackson -> https://github.com/FasterXML/jackson-bom
jetty -> https://github.com/eclipse/jetty.project/tree/jetty-9.4.x/jetty-bom
netty -> https://github.com/netty/netty/tree/4.1/bom
spring-framework -> https://github.com/spring-projects/spring-framework/tree/master/spring-framework-bom
reactor -> https://github.com/reactor/reactor

**Comment by swankjesse** [comment]
When this is done we will roll it out to our other open source projects.

**Comment by eddumelendez** [comment]
@swankjesse PR updated. I can help with the other projects :)

**Comment by swankjesse** [comment]
Yes please! Retrofit next?

**Pull request merged**
