### PR TITLE
Add @NotNull annotation to Interceptor

### PR DESCRIPTION
**Pull request by edenman**
(so Kotlin knows that params don't have to be optionals)

### CODE REVIEW

**Comment by swankjesse** [comment]
Weird. I think `@NotNull` should be the default. I’m not eager to change everything to match this.

**Comment by digitalbuddha** [comment]
will Kotlin recognize `@ParametersAreNonnullByDefault`? I believe you can add it at it to a `package-info.java`

**Comment by edenman** [comment]
Yeah, unfortunately Kotlin can't assume `@NotNull` by default and there doesn't seem to be a way to tell it that aside from one-off annotations.  AFAICT from [this](https://kotlinlang.org/docs/reference/java-interop.html#nullability-annotations), anyway.  I found a request for `@ParametersAreNonnullByDefault` support [here](https://youtrack.jetbrains.com/issue/KT-10942) but it hasn't had any activity or discussion yet. 

Not the end of the world if you don't want to accept this PR, i just thought it was worth proposing since I'm having to do a null check in my kotlin impl of an `Interceptor`.

**Comment by JakeWharton** [comment]
You can change the parameter type to non-nullable (since it's a platform
type and not a truly nullable type) and the null check will be emitted
automatically. Kotlin just defaults platform types to nullable when you use
the IDE to generate method implementation stubs for you.

**Comment by edenman** [comment]
oh, nice!  ignore me

**Pull request closed without merging**
