### PR TITLE
fix: StreamAllocation should keep route from reused connection

### PR DESCRIPTION
**Pull request by wuketidai**
fix for #3995

### CODE REVIEW

**Comment by swankjesse** [comment]
Thanks. The recent changes to StreamAllocation already fixed this, but the test is useful to defend regressions. Merged manually!

https://github.com/square/okhttp/commit/77f3cec493e09a704301b18d577ca7220e46231e

**Comment by wuketidai** [comment]
> Thanks. The recent changes to StreamAllocation already fixed this, but the test is useful to defend regressions. Merged manually!
> 
> [77f3cec](https://github.com/square/okhttp/commit/77f3cec493e09a704301b18d577ca7220e46231e)

Is it ok to merge this commit to branch 3.12.x? 
Do i need pull request again?

**Comment by swankjesse** [comment]
It's already done.

**Comment by swankjesse** [comment]
Nope, I misspoke. This isn't fixed in 3.12.x.

**Comment by wuketidai** [comment]
> Nope, I misspoke. This isn't fixed in 3.12.x.
 
Thanks. i got it. 
Because I can't upgrade to java8 now, It seems that I have to patch it for myself.

**Pull request closed without merging**
