### PR TITLE
support httpdns,verify hostname in header(if set) not get in url

### PR DESCRIPTION
**Pull request by lizhangqu**
If host is set in header,then replace host by the value in header(named headerHost).
When using https and httpdns,if get the host from url it will get an Exception (javax.net.ssl.SSLPeerUnverifiedException).
What is the httpdns ,see https://www.dnspod.cn/httpdns.
See more in recipes named HttpDns in okhttp-sample.

### CODE REVIEW

**Comment by swankjesse** [comment]
I don’t think this is worth supporting in the core library. But you can do what you like in interceptors. You might be able to use an application interceptor to rewrite the address OkHttp connects to, and another network interceptor to rewrite what host is sent once connected.

**Comment by swankjesse** [comment]
Scratch that, the network interceptor won’t let you rewrite the URL host. But it will let you set a custom Host header.

**Comment by lizhangqu** [comment]
Sorry,My English is poor.

When it connects by **domain** under the **https** protocol,there is **no problom**.
But if i connects by **ip**（this ip is get from **httpdns** before request,don't use **lcoaldns**）under the https,the ssl verify will get the host **from url**,now the host is ip,will throw an Exception named **javax.net.ssl.SSLPeerUnverifiedException**.

Sample:

If I want to connet the url [https://www.baidu.com](https://www.baidu.com),now using okhttp to connect ,there is no problem.

If I use httpdns to get the domain's ip before request,like this（also is a request）
```
http://119.29.29.29/d?dn=www.baidu.com
```

assert  the ip is 61.135.169.121.

I should replace the domain host by the ip(61.135.169.121) in application interceptors ,and will set a Header named Host,the header value is the domain(www.baidu.com)，now the request is  https://61.135.169.121 with a Host header(www.baidu.com),the ssl verify will get the host from url ,it means the host is ip(61.135.169.121) now,but in https certs,there is no ip,so throws javax.net.ssl.SSLPeerUnverifiedException.But if get the host from header(www.baidu.com) , now will get verified.Because there is a domain(www.baidu.com) in https certs.


Also if i use ip to connet,like this.
```
OkHttpClient okHttpClient = new OkHttpClient.Builder().build();
Request request = new Request.Builder()
        .url("https://220.181.112.244")
        .get()
        .build();
Response execute = okHttpClient.newCall(request).execute();

System.out.println(execute.body().string());
```

throws an Exception too.

**Comment by swankjesse** [comment]
Can you implement your own `Dns` class?

**Comment by swankjesse** [comment]
http://square.github.io/okhttp/3.x/okhttp/okhttp3/Dns.html

**Pull request closed without merging**
