### PR TITLE
Remove unused okhttp3.internal.cache2.Relay

### PR DESCRIPTION
**Pull request by amirlivneh**
I have no context on this. I'm only creating this PR since Redex flagged this internal code as unreachable, and it hasn't been touched in over 2 years.

Feel free to ignore this if the code is kept intentionally.

### CODE REVIEW

**Comment by swankjesse** [comment]
It's a work in progress!

**Comment by amirlivneh** [comment]
Cool, I'll close it then.

**Comment by yschimke** [comment]
is it better deleted and re-added as an open PR?  How dies this compare to okio BufferedSource.peek for the intended uses?

**Comment by swankjesse** [comment]
Peek is for a single thread to read twice. Relay is for any number of threads to each read once.

**Pull request closed without merging**
