### PR TITLE
update alpn for jdk8

### PR DESCRIPTION
**Pull request by iNoles**
build break if you used the latest version of jdk 8.

### CODE REVIEW

**Comment by swankjesse** [comment]
Excellent. We gotta update Travis too.

**Comment by iNoles** [comment]
@swankjesse 

```
addons:
  apt:
    packages:
      - oracle-java8-installer
```

**Comment by yschimke** [comment]
Working with that installer - https://github.com/square/okhttp/pull/2507

**Comment by swankjesse** [comment]
Awesome. Thanks @iNoles & @yschimke !

**Pull request closed without merging**
