### PR TITLE
Fix for conscrypt error (public api change)

### PR DESCRIPTION
**Pull request by yschimke**
Failing repeatedly in master nightly builds

https://app.circleci.com/pipelines/github/square/okhttp/3365/workflows/f6b1b06a-3141-4a7c-ae7c-aa6fc97e229f/jobs/14265
https://app.circleci.com/pipelines/github/square/okhttp/3330/workflows/7d8a2f66-2735-4daf-adcd-9620165e7b13/jobs/14069

### CODE REVIEW

**Comment by yschimke** [comment]
Noticed via https://github.com/square/okhttp/issues/6033

**Comment by yschimke** [comment]
Tested with `./gradlew -Dokhttp.platform=conscrypt okhttp-tls:test`

**Comment by swankjesse** [comment]
I’d prefer a different fix: catch the exception in OkHttp and wrap it in an unchecked exception.

The `CertificateParsingException` is a classic case of something that should have been an unchecked exception: it’s unlikely to ever fail in production code. And if it does, the application code should probably crash!

**Comment by yschimke** [comment]
Assuming review comments were a soft approve

**Comment by swankjesse** [comment]
Yep. LGTM.

**Pull request merged**
