### PR TITLE
Fix for JDK8 ALPN

### PR DESCRIPTION
**Pull request by yschimke**
Fix for https://github.com/square/okhttp/issues/6351

### CODE REVIEW

**Comment by yschimke** [comment]
```
$ javap -verbose okhttp/build/classes/kotlin/main/okhttp3/OkHttpClient.class | grep version
  minor version: 0
  major version: 52
```

**Comment by yschimke** [comment]
Test run in CI https://app.circleci.com/pipelines/github/square/okhttp/4293/workflows/4818d111-4b2c-44f1-964c-1b828e526439/jobs/19239/tests

**Review by swankjesse — APPROVED** [review]

**Comment by swankjesse** [comment]
Thanks!

**Comment by yschimke** [comment]
n.p. Please double check the artifacts in the RC1 to make sure we are publishing JDK8 class versions!

**Pull request merged**
