### PR TITLE
Remove superfluous throw

### PR DESCRIPTION
**Pull request by realdadfish**

### CODE REVIEW

**Review by JakeWharton — APPROVED** [review]

**Review by swankjesse — COMMENTED** [review]
I don't think this throw is superfluous; it tells both the reader and the compiler that control flow doesn't continue beyond invalidLengths. In particular, a statement inserted on line 983 was unreachable; now it's not.

**Comment by realdadfish** [comment]
The Nothing return type already told the compiler the same thing and therefor it spit out a warning on the call sites. TBH I would have found it more readable to just create the Exception in the method and not throw it inside there, but guessed this might be some kind of code style to follow.

**Comment by yschimke** [comment]
@swankjesse that was my first thought, but then seeing the Nothing response, I figured inside the IDE it's still clear it can't proceed.

Your call, want to revert?

**Comment by swankjesse** [comment]
Ahhh... returning nothing is enough, and my claim is wrong! Apologies for that! No action necessary.

**Comment by Kinou90100** [comment]
#7183
#7181
#7178
#7023
#6518
@Christoc90

**Pull request merged**
