### PR TITLE
Add link to okio proguard rules

### PR DESCRIPTION
**Pull request by StefMa**
Always when I search for the proguard rules of my app I jump from dependency to dependency.
okhttp makes it a little bit easier by saying "You also need the Okio rules".
But just saying it means I have to open a new tab, go to github.com/square/okio (or google it), and copy the stuff to my proguard files.

With that link we simplify the process 😇

### CODE REVIEW

**Comment by JakeWharton** [comment]
The rules are embedded now so there's no action to take on the consumer side. We should probably just delete this section.

**Comment by StefMa** [comment]
Is this true for proguard as well? 🤔

**Comment by JakeWharton** [comment]
Yes, provided you're using the Android Gradle plugin to run it.

**Comment by StefMa** [comment]
But maybe okhttp isn't used in an Android project but I'm a pure kotlin
project which uses proguard...
Then he needs to manually add these rules, right?

**Comment by JakeWharton** [comment]
Yes. But in that case I'm okay with the rules being a little harder to
find. The overwhelmingly common case is consuming and shrinking through AGP
and in that case copying rules is actually the worst outcome since they
inevitably become stale.

**Comment by JakeWharton** [comment]
A page on the website sounds okay. I don't think it's important enough to
put directly on the homepage though.

**Comment by StefMa** [comment]
✅ I moved it into the docs 👍 
See https://github.com/square/okhttp/pull/5541/commits/2260512dcf47cc294b493336fec753df77086ea4

**Pull request merged**
