### PR TITLE
Keep the cause when sending ConnectException

### PR DESCRIPTION
**Pull request by Tolriq**
Proposed fix for Issue #2881 

Keep the cause when sending ConnectException

### CODE REVIEW

**Comment by swankjesse** [comment]
Thanks! Merged manually.

**Comment by Tolriq** [comment]
@swankjesse for my culture as I'm still java noob.

Any reason for temp object versus the cast ?

I hesitated but went with what is shown in Javadoc for initCause.

**Comment by swankjesse** [comment]
The only difference is in style. I don’t like single-line `if` statements to be wrapped.

**Comment by Tolriq** [comment]
Ok thanks.

**Pull request closed without merging**
