### PR TITLE
Check for SSLSocketFactory set as SocketFactory

### PR DESCRIPTION
**Pull request by yschimke**

### CODE REVIEW

**Comment by swankjesse** [comment]
Clever!

**Comment by PromanSEW** [comment]
Thanks for breaking patch for Android SDK 16-19 enabling TLSv1.2 😕

**Comment by yschimke** [comment]
@PromanSEW Are you sure you still need this workaround?  This should be supported already via https://github.com/square/okhttp/commit/bdbe2dad8806a77bf018b87f4518df250fa67f89#diff-320161f78c8750690ba43fa6b21a5788

**Comment by PromanSEW** [comment]
@yschimke this fix does not work, I checked already

**Comment by PromanSEW** [comment]
I can provide the stacktrace of the crash

**Comment by PromanSEW** [comment]
```java
private static void enableSSL(@NonNull OkHttpClient.Builder builder) {
	ConnectionSpec.Builder spec = new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS);
	spec.tlsVersions(TlsVersion.TLS_1_2);
	if (Build.VERSION.SDK_INT >= 20) {
		spec.cipherSuites(CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256);
	} else {
		/*
		try { setSSLFactory(builder); }
		catch (Exception ignored) {}
		*/
	}
	builder.connectionSpecs(Collections.singletonList(spec.build()));
}

private static void setSSLFactory(@NonNull OkHttpClient.Builder builder)
		throws NoSuchAlgorithmException, KeyStoreException, KeyManagementException {
	TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
	tmf.init((KeyStore) null);
	X509TrustManager tm = Stream.of(tmf.getTrustManagers()).select(X509TrustManager.class).findFirst().orElse(null);
	if (tm == null) return;
	SSLContext context = SSLContext.getInstance(TLS12SocketFactory.TLS_1_2);
	context.init(null, new TrustManager[] { tm }, null);
	builder.sslSocketFactory(new TLS12SocketFactory(context.getSocketFactory()), tm);
}
```
Android 4.3:
```
java.net.UnknownServiceException: Unable to find acceptable protocols.
isFallback=false, modes=[ConnectionSpec(cipherSuites=[
TLS_AES_128_GCM_SHA256,
TLS_AES_256_GCM_SHA384,
TLS_CHACHA20_POLY1305_SHA256,
TLS_AES_128_CCM_SHA256,
TLS_AES_256_CCM_8_SHA256,
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
TLS_RSA_WITH_AES_128_GCM_SHA256,
TLS_RSA_WITH_AES_256_GCM_SHA384,
TLS_RSA_WITH_AES_128_CBC_SHA,
TLS_RSA_WITH_AES_256_CBC_SHA,
SSL_RSA_WITH_3DES_EDE_CBC_SHA
], tlsVersions=[TLS_1_2], supportsTlsExtensions=true)],
supported protocols=[SSLv3, TLSv1]
```

**Comment by PromanSEW** [comment]
Sorry, I did not understand the change in this PR. You have changed `socketFactory` method, not `sslSocketFactory` I used above

**Pull request merged**
