### PR TITLE
16 concurrent requests

### PR DESCRIPTION
**Pull request by yschimke**
Testing from discussion in https://github.com/square/okhttp/issues/907

### CODE REVIEW

**Comment by swankjesse** [comment]
I think if we’re gonna bump this, we might as well bump it to 16? Or check to see what Chrome does? Maybe Netty also?

**Comment by yschimke** [comment]
Does HTTP/2 ignore this and use the client/server negotiated stream limits?

**Comment by swankjesse** [comment]
No, that'll often be unbounded. We're trading off latency vs. throughput, cost of client threads, and load on server.

**Comment by yschimke** [comment]
What do you think about being somewhat adaptive?  Maybe having Platform indicate a rough device category or similar and retaining 5 for older devices? 16 for newer?

**Comment by swankjesse** [comment]
I think 16 is probably the right number for 2019. I'd just like to confirm we're in the same ballpark as Chrome, Firefox, and perhaps also Netty and libcurl.

**Comment by yschimke** [comment]
libcurl - unlimited https://curl.haxx.se/libcurl/c/CURLMOPT_MAX_HOST_CONNECTIONS.html by  default

**Comment by yschimke** [comment]
Firefox network.http.max-persistent-connections-per-server 6

**Comment by yschimke** [comment]
Chrome - 6 I believe, but couldn't easily find the exact config, most issues stop with a discussion we are sticking with 6 which Firefox also uses.

**Comment by yschimke** [comment]
Closing this out.  HTTP/2 is probably where we people concerned about the perf should focus on.  This is a separate control until we add load balancing.

**Comment by swankjesse** [comment]
Hang on. Those are limits on connections, not streams. I think maybe we need to make that distinction in our configuration?

**Comment by swankjesse** [comment]
Okay, idea time. The thing that makes 256 or 8192 concurrent requests unreasonable is client-side threads. And we need one client-side thread per client-side request due to our interceptors model.

But if we do suspendable interceptors, the number of client side threads and concurrent requests become decoupled.

**Comment by yschimke** [comment]
We should revisit, work out a more optimal number for mobile clients etc.  But likely it's more complicated than this PR as discussed above.

**Pull request closed without merging**
