### PR TITLE
Remove permitsRequestBody in HTTP Methods

### PR DESCRIPTION
**Pull request by EhsanMashhadi**
Remove permitsRequestBody in HTTP Methods to allow custom method with the body.
https://github.com/square/okhttp/issues/229

### CODE REVIEW

**Comment by EhsanMashhadi** [comment]
@swankjesse I have changed the code same as #229 but two tests are failed
```
URLConnectionTest.response308WithHead:2334->testRedirect:2373 expected:<[]> but was:<[Page 2]>
 URLConnectionTest.response307WithHead:2318->testRedirect:2373 expected:<[]> but was:<[Page 2]>
```

**Comment by yschimke** [comment]
For further discussion: I don't think removing this check is the right approach.  It might be that we should blacklist instead of whitelisting the special cases.  

Overall given the support for WEBDAV verbs, supporting previously unknown HTTP verbs seems appropriate, so I'm not against the sentiment of the change.

**Comment by EhsanMashhadi** [comment]
@yschimke  We are using lots of custom HTTP method in our projects, I have not seen any problem with using any custom verb with the body. Other rest clients like Alamofire in ios can do it now. Any plan for removing this restriction in a new version?

**Comment by yschimke** [comment]
My point wasn't around unknown custom verbs.  It was that allowing body for a GET request seems like a step back.

**Comment by yschimke** [comment]
I think https://github.com/square/okhttp/pull/3777 covers this

**Pull request closed without merging**
