### PR TITLE
Avoid sending empty HTTP/2 data frames when there is no request body.

### PR DESCRIPTION
**Pull request by dave-r12**
Closes: https://github.com/square/okhttp/issues/2892

### CODE REVIEW

**Comment by swankjesse** [comment]
Build failure is unrelated.
https://github.com/square/okhttp/issues/2997

**Comment by swankjesse** [comment]
(We might want a test for this.)

**Comment by dave-r12** [comment]
Agree on the testing. Did you have anything in mind? I didn't see a good way for adding a test as-is. One idea I was playing with was adding a listener for inbound HTTP/2 frames, and then checking no data frames were sent. It turned into a fair bit of change, so I withdrew. If you're receptive to the idea, I can follow up with something more concrete.

**Comment by swankjesse** [comment]
Yeah, good point. We lack visibility here. In RecordedRequest we track the chunk sizes for chunked encoding as list of integers. Maybe we populate that with frame sizes for HTTP/2?

**Comment by dave-r12** [comment]
Alright, I'll look into that, thanks.

**Pull request merged**
