### PR TITLE
Investigating #3146 and Avoid RST spam

### PR DESCRIPTION
**Pull request by yschimke**
Using this branch to try to replicate the socket timeouts in ExoPlayer in #3146

The test has two threads that flip flop - one making a request for a large range (80MB) and the other being mostly dormant.
The main test thread interrupts the active thread, and switches the other to active.

Trying to test that we

1) Don't accumulate open streams with active data transfer on them
2) See that cancellations are correctly sent
3) Don't see delays in between sending the request and getting the first byte back.

The first thing I noticed is that the flood of data packets, is matched with as many RST_STREAM packets to the server.  But presumably we only really need the first one?

```
1:Requesting
>> 0x00000000     6 SETTINGS      
>> 0x00000000     4 WINDOW_UPDATE 
>> 0x00000003    98 HEADERS       END_STREAM|END_HEADERS
<< 0x00000000    18 SETTINGS      
<< 0x00000000     4 WINDOW_UPDATE 
>> 0x00000000     0 SETTINGS      ACK
<< 0x00000000     0 SETTINGS      ACK
<< 0x00000003   674 HEADERS       END_HEADERS
<< 0x00000003 14880 DATA          
<< 0x00000003 16384 DATA          
1:Response in 376
1:First byte in 376
<< 0x00000003 16384 DATA          
<< 0x00000003 16372 DATA          
Open Streams 1
>> 0x00000003     4 RST_STREAM    
1:Interrupted 0
1:Finished
<< 0x00000003 16384 DATA          
1:Interrupted ignored
>> 0x00000003     4 RST_STREAM    
<< 0x00000003 16384 DATA          
2:Requesting
>> 0x00000003     4 RST_STREAM    
>> 0x00000005    47 HEADERS       END_STREAM|END_HEADERS
<< 0x00000003 16384 DATA          
>> 0x00000003     4 RST_STREAM    
<< 0x00000003 16384 DATA          
>> 0x00000003     4 RST_STREAM    
<< 0x00000003 16384 DATA          
>> 0x00000003     4 RST_STREAM    
<< 0x00000003 16384 DATA          
>> 0x00000003     4 RST_STREAM    
<< 0x00000003 16384 DATA          
>> 0x00000003     4 RST_STREAM    
<< 0x00000003 16384 DATA          
>> 0x00000003     4 RST_STREAM    
<< 0x00000003 16384 DATA          
>> 0x00000003     4 RST_STREAM    
<< 0x00000003 16384 DATA          
>> 0x00000003     4 RST_STREAM    
<< 0x00000003 16384 DATA          
>> 0x00000003     4 RST_STREAM    
<< 0x00000003 16384 DATA          
>> 0x00000003     4 RST_STREAM    
<< 0x00000003 16384 DATA          
>> 0x00000003     4 RST_STREAM    
<< 0x00000003 16384 DATA          
>> 0x00000003     4 RST_STREAM    
<< 0x00000003 16384 DATA          
>> 0x00000003     4 RST_STREAM    
<< 0x00000003 16384 DATA          
>> 0x00000003     4 RST_STREAM   
```

### CODE REVIEW

**Comment by yschimke** [comment]
As a temporary improvement to try to streamline this scenario, I've temporarily added.

```
  val cancelledStreams = mutableSetOf<Int>()

  internal fun writeSynResetLater(
    streamId: Int,
    errorCode: ErrorCode
  ) {
    if (cancelledStreams.add(streamId)) {
      writerQueue.execute("$connectionName[$streamId] writeSynReset") {
        try {
          writeSynReset(streamId, errorCode)
        } catch (e: IOException) {
          failConnection(e)
        }
      }
    }
  }
```

**Comment by yschimke** [comment]
cc @swankjesse

**Comment by yschimke** [comment]
I think not sending more RST_STREAM is covered by

>  However, after sending the
   RST_STREAM, the sending endpoint MUST be prepared to receive and
   process additional frames sent on the stream that might have been
   sent by the peer prior to the arrival of the RST_STREAM.

**Comment by yschimke** [comment]
How does the window accounting work? If we receive data for a stream and don't send a window update for the stream, do we still send for the connection?

**Comment by yschimke** [comment]
Looking at Http2ConnectionTest.readSendsWindowUpdateHttp2, i'd expect if client cancels the stream but receives data anyway that only one of the window updates is sent.

```
      peer.acceptFrame() // connection WINDOW UPDATE
//      peer.acceptFrame() // stream WINDOW UPDATE
```

**Comment by yschimke** [comment]
I think this test is too clean, it should start 10 threads with only one not cancelled.

**Comment by crazysouthern** [comment]
> Usando esta rama para intentar replicar los tiempos de espera del socket en ExoPlayer en #3146
> 
> La prueba tiene dos subprocesos que cambian: uno solicita un rango amplio (80 MB) y el otro está mayormente inactivo. El subproceso de prueba principal interrumpe el subproceso activo y cambia el otro a activo.
> 
> Tratando de probar que nosotros
> 
> 1. No acumule flujos abiertos con transferencia de datos activa en ellos
> 2. Ver que las cancelaciones se envíen correctamente
> 3. No vea retrasos entre el envío de la solicitud y la devolución del primer byte.
> 
> Lo primero que noté es que la avalancha de paquetes de datos coincide con la mayor cantidad de paquetes RST_STREAM en el servidor. ¿Pero presumiblemente solo necesitamos el primero?
> 
> ```
> 1:Requesting
> >> 0x00000000     6 SETTINGS      
> >> 0x00000000     4 WINDOW_UPDATE 
> >> 0x00000003    98 HEADERS       END_STREAM|END_HEADERS
> << 0x00000000    18 SETTINGS      
> << 0x00000000     4 WINDOW_UPDATE 
> >> 0x00000000     0 SETTINGS      ACK
> << 0x00000000     0 SETTINGS      ACK
> << 0x00000003   674 HEADERS       END_HEADERS
> << 0x00000003 14880 DATA          
> << 0x00000003 16384 DATA          
> 1:Response in 376
> 1:First byte in 376
> << 0x00000003 16384 DATA          
> << 0x00000003 16372 DATA          
> Open Streams 1
> >> 0x00000003     4 RST_STREAM    
> 1:Interrupted 0
> 1:Finished
> << 0x00000003 16384 DATA          
> 1:Interrupted ignored
> >> 0x00000003     4 RST_STREAM    
> << 0x00000003 16384 DATA          
> 2:Requesting
> >> 0x00000003     4 RST_STREAM    
> >> 0x00000005    47 HEADERS       END_STREAM|END_HEADERS
> << 0x00000003 16384 DATA          
> >> 0x00000003     4 RST_STREAM    
> << 0x00000003 16384 DATA          
> >> 0x00000003     4 RST_STREAM    
> << 0x00000003 16384 DATA          
> >> 0x00000003     4 RST_STREAM    
> << 0x00000003 16384 DATA          
> >> 0x00000003     4 RST_STREAM    
> << 0x00000003 16384 DATA          
> >> 0x00000003     4 RST_STREAM    
> << 0x00000003 16384 DATA          
> >> 0x00000003     4 RST_STREAM    
> << 0x00000003 16384 DATA          
> >> 0x00000003     4 RST_STREAM    
> << 0x00000003 16384 DATA          
> >> 0x00000003     4 RST_STREAM    
> << 0x00000003 16384 DATA          
> >> 0x00000003     4 RST_STREAM    
> << 0x00000003 16384 DATA          
> >> 0x00000003     4 RST_STREAM    
> << 0x00000003 16384 DATA          
> >> 0x00000003     4 RST_STREAM    
> << 0x00000003 16384 DATA          
> >> 0x00000003     4 RST_STREAM    
> << 0x00000003 16384 DATA          
> >> 0x00000003     4 RST_STREAM    
> << 0x00000003 16384 DATA          
> >> 0x00000003     4 RST_STREAM   
> ```

**Comment by yschimke** [comment]
Google Translate:

> Using this branch to try to replicate socket timeouts in ExoPlayer in #3146
> 
> The test has two threads that switch: one requests a wide range (80MB) and the other is mostly idle. The main test thread kills the active thread and makes the other active.
> 
> Trying to prove that we
> 
>     Don't accumulate open streams with active data transfer on them
>     See that cancellations are sent correctly
>     See no delays between sending the request and returning the first byte.
> 
> The first thing I noticed is that the flood of data packets coincides with the largest number of RST_STREAM packets on the server. But presumably we only need the first one?

**Comment by crazysouthern** [comment]
Te diré

**Comment by yschimke** [comment]
Will use for testing after #7023 lands

**Pull request closed without merging**
