### PR TITLE
Official Gradle Wrapper Validation GitHub Action

### PR DESCRIPTION
**Pull request by JLLeitschuh**
See: https://github.com/gradle/wrapper-validation-action

### CODE REVIEW

**Comment by JakeWharton** [comment]
Thanks!

**Comment by JakeWharton** [comment]
lol

> ```
> ### ERRORED 19:52:50Z
>
> - Workflows can't be executed on this repository. Please check your payment method or billing status.
> ```

@swankjesse cashapp/okhttp plz?

**Comment by JLLeitschuh** [comment]
Should be free for open source projects, regardless of how your financial stuff is setup for your organization. I'm guessing this is a bug?

**Comment by JLLeitschuh** [comment]
I've let the people at GitHub know about this.

**Comment by swankjesse** [comment]
Square is on a legacy GitHub account that doesn’t support actions.

**Pull request merged**
