### PR TITLE
google-oss-license support

### PR DESCRIPTION
**Pull request by iNoles**
Added support of google-oss-license that couldn't read from parent's pom files.

### CODE REVIEW

**Comment by yschimke** [comment]
This should work for tooling that is using the maven model, is there an example where this isn't working? Some popular license check tools?

```
$ mvn help:effective-pom | grep -A 2 license
  <licenses>
    <license>
      <name>Apache 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>
  <scm>
    <connection>scm:git:https://github.com/square/okhttp.git/okhttp-urlconnection</connection>
```

**Comment by JakeWharton** [comment]
Yeah I don't think we want this. Same PR was made to Retrofit. It's the new
[weird, bad] plugin in Play Services. I'd rather push it to them to fix.
The license is in the parent pom and they should resolve that and check.

**Comment by yschimke** [comment]
@iNoles closing for now, but reopen if you want to discuss further.

**Comment by JakeWharton** [comment]
I filed an issue internally about this. Going to wait to see what they say.

**Pull request closed without merging**
