### PR TITLE
Add charset support for Credentials.basic

### PR DESCRIPTION
**Pull request by erikghonyan**
Issue #2911, #1468

### CODE REVIEW

**Comment by swankjesse** [comment]
I don’t think this is consistent with the spec.
https://datatracker.ietf.org/doc/rfc7617/

**Comment by erikghonyan** [comment]
Well, if I understand correctly the spec doesn't really force any charset.

>    The original definition of this authentication scheme failed to
>    specify the character encoding scheme used to convert the user-pass
>    into an octet sequence.  In practice, most implementations chose
>    either a locale-specific encoding such as ISO-8859-1 ([ISO-8859-1]),
>    or UTF-8 ([RFC3629]).  For backwards compatibility reasons, this
>    specification continues to leave the default encoding undefined, as
>    long as it is compatible with US-ASCII (mapping any US-ASCII
>    character to a single octet matching the US-ASCII character code).

And according to the following paragraph the only reason not to switch to UTF-8 completely is because there are sites that don't use UTF-8 and won't work with UTF-8.

> B.3.  Why not simply switch the default encoding to UTF-8?
> 
>    There are sites in use today that default to a local character
>    encoding scheme, such as ISO-8859-1 ([ISO-8859-1]), and expect user
>    agents to use that encoding.  Authentication on these sites will stop
>    working if the user agent switches to a different encoding, such as
>    UTF-8.
> 
>    Note that sites might even inspect the User-Agent header field
>    ([RFC7231], Section 5.5.3) to decide which character encoding scheme
>    to expect from the client.  Therefore, they might support UTF-8 for
>    some user agents, but default to something else for others.  User
>    agents in the latter group will have to continue to do what they do
>    today until the majority of these servers have been upgraded to
>    always use UTF-8.

So if the server supports UTF-8, shouldn't we allow the clients to use that charset? The patch doesn't change the default charset, it's still ISO-8859-1, but if the clients want to use UTF-8 they can.

**Comment by swankjesse** [comment]
Yep, you’re right. I’m sorry, I was misreading this thinking it’s the clients that specify a `charset` parameter. I’m wrong; that’s the server’s job.

Any thoughts on whether this should take a `Charset` instead of a `String` to identify the charset? I like the strongly-typed one myself because it discourages clients from passing through garbage from the incoming `Challenge` header.

**Comment by erikghonyan** [comment]
Actually that's what I wanted to do at first! I like strongly-typed code too, just didn't want to make too many changes :) Updated the patch.

**Comment by swankjesse** [comment]
Thanks!

**Comment by erikghonyan** [comment]
@swankjesse I think we should close #1468

**Comment by swankjesse** [comment]
Should we add `charset` to `Challenge` ?

**Comment by erikghonyan** [comment]
Here you go #3144

**Pull request merged**
