### PR TITLE
Recover from a coalesced connection that immediately goes unhealthy.

### PR DESCRIPTION
**Pull request by dave-r12**
I'm not sure, does it make sense to put this in 3.14.X?

### CODE REVIEW

**Comment by swankjesse** [comment]
Heck yes it does. Thank you!

**Comment by dave-r12** [comment]
Ahh shoot, we ran outta memory during the build!

```
[ERROR] requestBodyFailHttp2OverHttps(okhttp3.EventListenerTest)  Time elapsed: 233.565 s  <<< ERROR!
java.lang.OutOfMemoryError: Java heap space
	at okhttp3.EventListenerTest.requestBodyFail(EventListenerTest.java:1009)
	at okhttp3.EventListenerTest.requestBodyFailHttp2OverHttps(EventListenerTest.java:975)
```

**Comment by swankjesse** [comment]
Are we looping indefinitely?

**Comment by swankjesse** [comment]
Nah, @oldergod just changed the test from 8 MiB to 256 MiB which is too much. Unrelated to this PR!

**Pull request merged**
