### PR TITLE
Fix javadoc on setProtocols method.

### PR DESCRIPTION
**Pull request by IgorGanapolsky**

### CODE REVIEW

**Comment by swankjesse** [comment]
What’s wrong with the current doc?

**Comment by swankjesse** [comment]
(maybe we want `{@linkplain ...}` instead of `{@link ...}`)

**Comment by IgorGanapolsky** [comment]
I believe the curly brace was at the wrong place for @link reference in
that method.

**Comment by JakeWharton** [comment]
+1 to `{@linkplain ..}`. The `}` was in the correct place.

**Comment by IgorGanapolsky** [comment]
Updated to linkplain.

**Pull request closed without merging**
