### PR TITLE
Modify for-loop more performance sensitively

### PR DESCRIPTION
**Pull request by shaunkawano**
I happen to find one for-loop that can be written more performance sensitively, based on this: 

https://speakerdeck.com/jakewharton/eliminating-code-overhead-square-hq-2015

### CODE REVIEW

**Comment by swankjesse** [comment]
Thanks.

**Comment by iNoles** [comment]
This one used 
```java
for (int i = 0; i < size; i++) {
```
than
```java
for (int i = 0, size = list.size(); i < size; i++) {
```

I thought first one wasted more memory than 2nd one.

**Comment by swankjesse** [comment]
The second form is generally favorable. In this case the first is okay because we avoid making two calls to `list.size()`.

**Comment by swankjesse** [comment]
... because we use size() both in the loop and also to pre-size an `ArrayList.`

**Pull request merged**
