### PR TITLE
Add Travis CI link to the main page

### PR DESCRIPTION
**Pull request by yschimke**

### CODE REVIEW

**Comment by yschimke** [comment]
image

**Comment by yschimke** [comment]
Yep. I’ll close. N.b. Was broken today based on potentially flaky test.

**Comment by swankjesse** [comment]
Cool. Yeah I think _we_ wanna track those and fix ’em. I’d hate for our users to see “Failing” and worry because Travis is a little more sensitive and our tests are a little more fragile than we want.

**Comment by JakeWharton** [comment]
I too am against badges. It's either always green it always something we don't want to show our users.

**Comment by yschimke** [comment]
Was going for something tasteful image

**Comment by yschimke** [comment]
A (quick, maybe buggy) query over travis build results

```
16:43 $ ~/Dropbox/oksocial/builds.kts square/okhttp
✓✓✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓✓❌✓✓✓✓✓❌✓❌??✓✓?✓✓✓✓?✓✓✓✓✓✓✓❌❌?✓✓❌✓✓✓✓✓✓✓✓✓✓❌✓❌?✓✓✓✓✓✓✓?✓❌✓✓✓✓✓✓
✓✓✓✓??✓✓✓✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓?❌❌✓❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌✓✓?✓❌✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓?✓
✓✓❌?✓✓✓❌✓✓✓?❌✓✓✓✓?✓✓✓??✓✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓❌?✓✓✓✓✓✓??✓✓✓✓✓✓✓???✓✓?
✓??❌✓???❌❌✓✓?✓✓✓✓✓✓✓✓?✓✓??✓✓✓✓✓✓✓✓✓✓✓✓❌✓❌❌✓❌??✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓?✓✓?❌❌❌❌❌❌❌❌❌❌❌❌❌
❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓❌✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓✓?✓✓✓✓❌
❌❌✓❌❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓?✓✓✓✓✓✓✓✓✓?✓✓?✓?✓✓✓✓✓??✓✓✓✓✓✓✓✓?✓✓?✓✓?✓✓✓✓✓✓❌✓✓✓
✓✓✓❌✓✓✓✓✓✓✓✓✓❌✓✓✓✓✓✓✓?✓?✓✓??❌?✓✓✓✓✓?✓✓✓✓✓✓✓❌✓????✓❌✓✓✓✓❌❌✓❌✓✓✓✓✓✓?✓??✓?✓✓✓???✓??
❌✓✓?✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓❌✓✓✓✓✓❌❌✓✓✓✓?✓✓✓✓❌✓✓✓✓✓✓✓✓✓✓❌✓❌✓✓✓✓✓✓✓✓✓?✓✓✓✓✓✓✓✓✓✓✓✓?✓✓✓✓
✓?✓✓✓✓✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓❌✓✓✓✓❌✓✓✓❌✓❌✓✓✓✓✓❌✓✓❌❌✓❌✓❌❌❌✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
✓✓?✓✓✓✓✓✓✓✓✓✓?✓✓✓✓✓✓✓❌✓✓✓❌✓?✓✓✓✓✓?✓✓✓✓❌✓✓✓❌✓✓✓✓✓❌✓✓✓✓✓✓✓✓?✓✓❌❌❌❌✓?❌✓✓✓❌❌✓✓✓✓✓✓✓❌
??❌❌✓✓❌?✓✓✓❌?✓?✓?❌✓✓✓✓❌?✓✓✓✓❌✓✓✓✓??✓✓✓✓✓❌✓✓✓✓✓?✓✓✓✓✓✓❌✓✓✓✓❌✓❌❌❌✓✓?✓✓✓✓✓✓✓✓✓✓✓✓✓✓
✓✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓?✓✓✓✓✓✓?✓✓✓✓?✓✓?✓✓✓✓✓❌?✓??✓✓✓✓?✓✓✓✓✓✓✓✓
✓✓✓✓✓✓✓✓✓✓✓✓?✓✓✓?✓✓✓✓?❌❌✓✓✓?✓?✓✓❌✓✓✓✓✓✓❌✓✓✓✓✓✓✓?✓✓✓✓✓?✓✓✓✓✓?❌❌?✓✓✓✓✓❌✓✓?✓✓✓???✓?
✓❌??✓?✓✓✓✓✓✓✓✓❌✓✓❌✓✓?✓✓✓✓✓✓??✓❌✓✓✓✓✓✓✓✓?✓❌✓✓✓✓✓✓✓✓✓?✓✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓?✓✓✓✓
✓✓✓✓✓✓✓✓✓✓✓✓✓✓????✓????✓?✓✓✓✓❌❌❌?✓✓✓?✓✓✓✓✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓?✓✓✓?✓✓✓✓✓?✓✓✓
✓✓✓✓✓❌✓✓❌❌❌❌❌✓✓??✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓?✓??✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
?✓✓✓?✓✓❌✓✓✓✓❌✓?✓✓✓✓✓?✓✓✓✓?✓✓??✓✓✓✓✓✓✓✓✓✓??✓❌?✓✓?✓✓✓?✓✓??❌✓✓❌❌✓❌?✓✓?✓✓✓✓✓✓✓??✓✓✓?
✓?✓✓✓✓✓✓✓✓?✓✓?✓✓✓✓✓✓✓?✓✓?❌✓✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓✓✓?✓✓✓❌✓✓✓✓❌✓✓✓✓✓❌✓?✓✓✓✓✓✓?✓✓✓✓✓✓✓?✓✓✓
✓✓?✓❌❌✓❌?❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓?❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓❌✓✓✓✓❌✓✓✓✓✓❌❌❌❌✓✓✓✓❌✓?✓✓✓✓✓✓❌❌❌❌❌✓✓✓✓✓
✓❌❌✓❌❌✓✓✓✓✓✓✓✓✓✓✓✓❌✓✓✓?✓✓✓✓✓✓?✓✓?✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓❌✓✓✓✓?✓?✓✓✓✓✓?✓✓✓✓✓?✓✓?✓✓?✓✓✓❌✓✓
✓✓✓✓✓✓✓✓✓✓✓✓?✓✓❌✓✓✓?✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓?✓✓✓✓✓✓✓??✓✓❌??✓✓✓✓✓❌?✓✓✓✓✓✓✓✓?✓✓✓❌✓✓✓✓✓✓✓?✓✓
✓✓✓✓✓✓?✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓??✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓?✓✓✓✓✓✓✓?✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓?✓✓???✓?✓
✓✓✓✓✓✓✓✓✓✓✓✓✓✓?✓??✓??????????✓✓✓?✓✓✓✓✓❌✓✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓?✓✓✓✓✓✓✓✓✓✓✓✓❌✓
✓✓✓✓?✓✓✓✓??✓✓✓✓✓✓?✓✓?✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓?❌❌❌❌❌❌❌✓❌❌❌❌✓❌❌❌❌❌✓❌❌✓✓❌✓?✓✓✓✓✓✓✓?✓✓✓❌✓✓??✓
?✓✓✓✓✓✓❌✓✓✓❌❌✓✓✓?✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓✓✓?✓✓✓✓✓❌?✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓❌✓✓✓✓❌✓
✓✓✓❌✓✓❌✓❌✓✓✓✓?✓✓✓✓✓✓✓✓✓?✓✓✓❌?✓✓❌❌✓✓✓✓❌❌✓✓✓✓✓✓✓✓✓✓✓✓❌✓✓✓✓✓❌✓❌❌✓✓?✓✓??✓✓✓✓✓?✓✓✓✓✓✓
✓❌✓✓✓✓✓✓✓✓✓✓???✓✓❌✓✓✓✓❌✓✓✓✓✓✓✓???✓✓?✓?✓✓?????✓?✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓?✓✓?✓✓✓✓✓✓✓✓✓✓✓
✓✓✓✓✓✓??✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓?✓✓❌❌✓✓✓✓✓✓✓✓✓✓✓✓??✓✓✓✓✓✓✓✓✓✓✓✓✓✓??✓✓???❌✓✓✓✓✓✓✓
✓✓??✓✓✓✓✓✓✓??✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓?✓✓✓✓✓?✓✓✓✓✓✓✓❌❌?❌✓✓❌❌❌❌❌✓✓✓✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓?
✓✓✓✓??❌?❌?✓✓?✓✓❌?✓✓✓✓?✓✓?✓✓??❌??✓✓✓✓✓✓✓??✓✓✓❌?✓✓?✓????✓✓✓✓✓✓✓?✓✓✓?✓✓✓✓✓?✓?✓✓?✓?✓
✓✓?✓✓?✓??✓✓✓✓✓?❌❌❌✓??????✓?✓✓✓✓✓??✓✓✓❌✓✓?✓✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓?✓✓?✓?✓✓✓✓✓✓?✓?❌✓?✓?
?✓??✓✓✓?✓✓??✓✓✓❌✓✓?✓✓✓✓✓✓✓❌✓❌❌✓✓✓??????❌❌???✓✓?✓✓?✓✓✓✓❌✓✓❌❌✓✓?✓✓?✓??✓✓??✓✓✓?✓✓❌?
✓????❌?✓❌??✓???✓??✓✓✓?✓✓✓✓✓✓✓✓✓✓✓✓✓?✓✓✓✓✓✓?✓?✓✓✓✓❌❌?✓❌?✓✓✓?✓✓❌?✓✓✓✓✓????????✓✓✓✓
✓✓❌✓?✓✓????❌❌✓?✓✓✓?✓????✓✓?❌??✓✓?✓✓??✓✓✓✓✓✓?✓✓????✓?✓✓✓?✓??✓✓✓✓???✓✓?✓???✓✓✓?✓✓✓
??✓✓✓??❌✓✓??✓✓✓✓???✓✓✓?✓?✓✓✓✓?????✓✓✓✓?❌✓✓✓✓❌✓❌✓?✓?✓✓?✓❌❌❌❌✓✓❌✓✓✓✓❌?✓?✓✓✓✓❌❌❌?✓?
✓✓❌??❌?❌❌❌✓❌❌❌✓❌?❌✓?❌✓???✓✓?✓❌❌✓❌✓✓❌❌???✓???✓✓❌✓??❌??✓✓✓✓?❌❌✓✓✓✓✓✓✓✓❌❌???✓✓✓✓✓❌✓
✓✓✓✓?✓✓✓✓✓✓✓✓??✓??✓✓❌❌?✓✓❌✓❌?????✓✓✓✓✓✓??❌❌❌??❌??????❌❌❌❌??❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌
❌❌❌❌❌❌❌❌❌?❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌?❌❌??❌?❌❌❌?❌❌❌❌❌❌❌❌?❌?❌❌?❌❌❌❌❌❌❌❌❌❌??❌?❌❌❌❌❌
❌?❌?❌❌❌?❌❌??❌❌❌❌❌??❌❌❌?❌?❌❌❌❌❌❌?❌❌❌❌❌❌❌?❌❌❌❌?❌❌❌❌❌❌❌❌❌❌❌❌??❌???❌?❌❌❌❌❌❌❌?❌?❌❌❌?❌
???????❌??❌❌❌❌❌❌❌❌?❌?❌❌?❌❌??❌?❌???❌?❌❌?❌❌❌?????❌??❌❌❌❌❌?❌❌??❌??❌❌❌??❌❌❌❌❌❌✓❌❌❌❌✓
❌❌❌✓❌❌✓❌❌✓?❌❌✓✓❌❌❌✓✓✓❌❌✓✓❌❌✓✓✓✓✓❌❌❌✓❌✓❌❌❌❌❌✓??✓?❌✓?✓❌?✓❌✓❌✓❌❌❌❌✓❌❌❌❌❌❌✓✓❌❌✓❌❌❌✓?
❌?✓❌❌❌❌❌✓✓❌❌✓✓?❌?❌❌✓✓❌❌❌✓✓✓✓?✓❌❌❌❌?❌❌❌❌❌?✓✓✓❌❌✓✓❌❌✓✓✓❌❌?❌❌❌✓❌❌✓✓❌❌✓✓❌✓❌❌✓✓❌❌✓✓❌✓
❌❌❌✓❌❌❌?✓✓??❌❌✓❌❌❌❌✓✓❌❌✓✓❌?❌❌❌❌❌✓❌❌✓❌❌❌❌❌?✓❌❌❌❌✓✓❌❌✓❌❌✓✓✓❌❌✓❌✓❌?✓✓❌❌✓❌❌✓❌❌✓❌❌❌❌?
❌❌❌❌❌❌✓❌✓❌✓❌❌❌?❌?✓❌❌❌❌✓❌❌✓❌❌❌❌✓?✓❌❌❌❌❌❌❌✓✓❌❌❌❌✓❌❌✓❌❌❌❌✓❌❌✓✓❌✓✓✓✓❌❌?❌✓✓?❌❌❌✓✓❌❌❌✓
❌❌✓✓❌✓❌❌❌❌✓❌✓✓✓?✓❌✓❌❌❌❌✓❌❌?❌❌❌❌✓❌❌✓✓✓✓❌❌✓❌❌❌❌❌❌❌❌✓❌✓✓❌✓❌✓?❌?❌❌?❌❌❌❌❌❌❌❌?❌❌❌❌❌❌❌❌
❌?✓✓❌✓✓❌?✓❌❌✓❌❌❌❌❌❌❌✓✓✓❌❌❌❌✓✓?✓✓❌✓✓✓✓✓✓✓✓✓❌❌✓❌✓✓✓✓❌✓?✓✓✓✓❌✓✓✓❌❌✓✓✓✓✓❌✓❌❌✓✓✓❌❌✓✓✓
✓❌✓?✓?❌✓✓✓✓✓✓✓✓✓❌❌✓✓❌✓✓✓✓✓?✓✓✓✓✓✓✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓✓❌✓✓✓✓✓✓✓❌✓✓?✓✓✓?✓✓✓❌✓✓✓❌✓✓✓✓✓✓✓
✓✓✓✓✓✓✓✓✓✓???✓?✓✓✓✓✓✓✓✓❌✓❌✓✓✓✓✓✓✓✓✓✓❌????❌?✓?????✓✓✓❌?✓✓✓✓✓✓✓❌✓✓??✓✓✓?✓❌✓???✓??✓
?✓✓❌✓??✓✓?✓❌✓✓✓✓✓?✓✓✓✓?✓?✓✓?✓✓✓?✓???✓❌✓✓✓✓✓✓❌✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓✓???✓?✓✓✓❌?✓✓✓✓?✓✓?✓
✓✓✓❌✓?✓✓?❌✓?✓✓✓✓?✓✓?❌???✓✓???✓✓✓✓?✓✓✓✓✓✓❌✓❌?✓❌✓✓✓??✓✓❌?❌?✓?✓✓✓✓✓✓✓??✓✓✓✓✓✓?❌✓?✓✓
✓✓?✓?✓✓✓❌✓✓✓✓✓✓✓✓?✓✓✓✓✓?✓✓✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓❌✓✓✓✓✓✓✓✓✓✓✓✓❌❌✓✓?❌?✓✓✓??
✓?✓❌?✓❌?✓??❌?✓???❌????✓????❌❌?????????❌????????❌?❌??????????✓??❌✓?✓✓✓✓✓?✓✓❌❌✓✓??
?✓???????✓✓???✓✓❌❌✓??✓?✓✓✓✓???❌❌?❌❌?✓?✓??✓???????????????✓?✓?✓✓✓✓?✓?❌??✓✓?❌?❌✓✓?
?✓✓?✓✓✓✓?✓✓✓❌?✓?✓?✓?✓?✓✓?✓?✓✓?✓✓✓✓✓?✓?✓✓??✓✓✓??✓✓??✓✓✓✓✓✓??✓✓❌✓?✓✓✓❌❌✓✓??✓?✓✓✓❌✓
✓✓?❌✓❌✓✓❌✓✓❌?✓❌??✓?✓✓✓✓✓✓✓✓✓?✓✓✓?✓✓?✓✓✓✓✓??✓✓✓✓?❌❌✓✓✓❌?✓✓❌??❌✓✓❌❌❌✓✓?✓?????✓?✓✓✓
✓❌?❌?❌✓❌✓✓✓✓✓✓✓✓?✓✓?✓✓?✓✓✓✓❌✓?✓?✓✓❌?✓✓??✓??✓✓✓???✓✓??✓❌?✓✓✓✓??✓???✓?✓✓✓?✓❌✓✓?✓✓✓
???❌❌❌✓????❌?✓?✓✓?✓✓✓✓✓?✓?❌?????✓✓?✓✓✓✓❌?✓✓✓✓✓????✓❌?????❌❌❌❌???✓✓❌❌✓✓✓❌❌??✓✓❌✓✓
✓✓✓❌✓✓✓✓✓✓?✓?❌✓?✓✓✓✓❌✓❌✓✓✓✓❌❌✓✓✓?✓✓✓✓❌✓✓✓✓✓✓❌❌❌❌✓❌?????❌✓✓?✓✓✓✓?✓✓✓??❌✓?✓?✓✓✓?✓✓
?✓✓?✓?❌❌✓✓✓✓??✓✓???✓✓?✓✓✓✓✓✓✓✓✓✓?✓✓✓???❌❌❌??✓✓??✓??❌✓✓✓✓✓✓?✓?✓✓✓✓✓✓✓?✓✓✓✓✓?✓✓?✓?
✓❌❌❌✓?✓✓?❌✓✓✓✓?✓✓✓✓✓✓?❌✓✓✓✓✓✓?✓✓✓??✓✓✓❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌✓❌❌❌❌❌❌❌❌❌❌❌❌❌✓❌❌❌
❌❌❌❌❌❌❌❌❌❌❌❌❌❌✓❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌✓❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌
❌❌✓❌✓❌❌❌❌❌❌✓❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌✓❌❌❌❌❌❌❌❌❌❌❌✓✓❌❌❌❌❌❌✓❌?❌❌❌❌
❌❌❌❌❌❌❌❌❌❌❌?❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌
❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌?❌❌❌??????????????????????????????????????????????????????????
???????????????????
```

**Pull request closed without merging**
