### PR TITLE
Conscrypt 2.0.0 Upgrade

### PR DESCRIPTION
**Pull request by yschimke**

### CODE REVIEW

**Comment by swankjesse** [comment]
https://github.com/google/conscrypt/issues/628

**Comment by swankjesse** [comment]
https://groups.google.com/forum/m/#!topic/conscrypt/9pWT0dux13A

**Comment by yschimke** [comment]
@swankjesse Yep, sorry I should have posted this context.  one of the earlier commits accounted for both changes, before I realised that as this is an optional dependency there was probably more value in keeping it compatible for now.  Hence silencing the deprecation warning.

**Comment by swankjesse** [comment]
Awesome. Ship it!

**Pull request merged**
