### PR TITLE
Android CI variants

### PR DESCRIPTION
**Pull request by yschimke**
Try to set an optimal set of builds from 

https://en.wikipedia.org/wiki/Android_version_history

and

https://androiddistribution.io/#/

### CODE REVIEW

**Comment by yschimke** [comment]
In Github seeing failures on 26 like

```

447
> Task :android-test:connectedDebugAndroidTest
448
Starting 0 tests on test(AVD) - 8.0.0
449
Tests on test(AVD) - 8.0.0 failed: Instrumentation run failed due to 'Process crashed.'
```

**Comment by yschimke** [comment]
```
Warning: Failed to find package 'system-images;android-31;default;x86'
```

**Comment by yschimke** [comment]
I've seen enough signs to indicate that different Android versions are flaky in different ways.  Going to land this to unblock using PRs + CI builds for Android related changes.

**Comment by yschimke** [comment]
@swankjesse requesting post review

**Review by swankjesse — COMMENTED** [review]
LGTM

This change doesn’t match the PR description.

**Comment by swankjesse** [comment]
LGTM

Ahh, now reading the notes I understand. Makes sense.!

**Comment by yschimke** [comment]
Sorry, I know I can be a bit disorganized with PRs.

The commit went in as "Reduce Android CI variants"

https://github.com/square/okhttp/commit/d0b795a87bb1976ed365dc2840a84e184a9fdea4

**Review by jj-crypto — APPROVED** [review]

**Pull request merged**
