### PR TITLE
Only get proxy if using proxyAuthorization in JavaNetAuthenticator.au…

### PR DESCRIPTION
**Pull request by jsoref**
…thenticate (#3809)

### CODE REVIEW

**Comment by jsoref** [comment]
@swankjesse : is there anything I need to do to get this to progress?

**Comment by swankjesse** [comment]
Yeah I can take a look soon.

**Comment by Aks-4125** [comment]
@jsoref can you please tell me how did you do **mvn clean verify**. I am newbie for contribution and one of my PR failed for this repository. can you please give me any reference link? Thanks :)

**Comment by jsoref** [comment]
@Aks-4125 : I don't understand the question. I'm going to reply in #3833

**Comment by swankjesse** [comment]
I’m going to fix this by fixing the underlying problem – we shouldn’t pass a null route to the authenticator.
https://github.com/square/okhttp/pull/3840

**Comment by swankjesse** [comment]
Thanks for surfacing this, and sorry about the bug!

**Comment by swankjesse** [comment]
Gotcha. OkHttp won't do keep and re-send the authorization header, but you can add it in a few lines with an interceptor.

**Pull request closed without merging**
