### PR TITLE
 Convert AddressTest to Kotlin

### PR DESCRIPTION
**Pull request by TangHuaiZhe**
Convert AddressTest to Kotlin.
All four tests passed.
Code style follow [square/java-code-styles](https://github.com/square/java-code-styles)

### CODE REVIEW

**Comment by yschimke** [comment]
Moving tests like these is premature. These currently function as Java source compatibility regression tests. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TangHuaiZhe** [comment]
> Moving tests like these is premature. These currently function as Java source compatibility regression tests.
> 
> Sent with [GitHawk](http://githawk.com)

I find `Address.java`  was already  converted to Kotlin , so I changed the AddressTest.
Should I close the pull request?

**Comment by yschimke** [comment]
We need specific Public API coverage for both Kotlin and Java before we refactor these.  Also there is less priority for moving existing tests and it introduces some risk when trying to ensure we don't have regressions between 3.14 and 4.0.

**Comment by swankjesse** [comment]
Yes. No plans to migrate tests.

**Pull request closed without merging**
