### PR TITLE
Add a shield for Codota code search for okhttp

### PR DESCRIPTION
**Pull request by drorweiss**
Semantic code search for OkHttp is now available at Codota at https://www.codota.com/xref/#/github_square_okhttp_560dae058b9d0b03006e7e97/findUsages 
For example, see [usages for class OkHttpClient and its methods](https://www.codota.com/xref/#/github_square_okhttp_560dae058b9d0b03006e7e97/findUsages?query=com.squareup.okhttp.OkHttpClient)

I hope it's going to help people reading this code. Looking forward for feedback.

### CODE REVIEW

**Comment by drorweiss** [comment]
Hi there - I see that my pull request for the readme was rejected.
Can you share the reason why?
I truly believe that Codota semantic code search (link in the original comment) will provide value to people reading the code in this repo.
Thanks

**Comment by swankjesse** [comment]
We don't allow advertising on our README.

**Comment by drorweiss** [comment]
OK, I understand, that wasn't the purpose. 
We still welcome okhttp users to search the project code on Codota. If there's a legitimate way to let people reading the code in this repo know that this possibility exists, I'd be happy mention it *somewhere* (e.g. CODESEARCH.md) or where you guys see fit.

**Comment by swankjesse** [comment]
If you want to draw attention to your product, you should buy ads on StackOverflow. If your product is good enough to use, it's good enough to advertise.

**Pull request closed without merging**
