### PR TITLE
[WIP] Test with TaskQueue event logging

### PR DESCRIPTION
**Pull request by yschimke**
Testing logging task queue events for @Flaky tests

TODO
- decent API
- remove duplication
- possibly merge TestRules?
- log format

### CODE REVIEW

**Comment by yschimke** [comment]
Example events from WholeOperationTimeoutTest.noTimeout

```
Events (28)
[0 ms] callStart: Request{method=POST, url=http://localhost:52422/}
[4 ms] proxySelectStart: http://localhost:52422/
[5 ms] proxySelectEnd: [DIRECT]
[8 ms] dnsStart: localhost
[8 ms] dnsEnd: [localhost/127.0.0.1]
[11 ms] connectStart: localhost/127.0.0.1:52422 DIRECT
FINE: Q2 scheduled after 0 µs: MockWebServer /127.0.0.1:52423
FINE: Q2 starting: MockWebServer /127.0.0.1:52423
[17 ms] connectEnd: http/1.1
FINE: Q1 scheduled after 0 µs: OkHttp ConnectionPool
FINE: Q1 starting: OkHttp ConnectionPool
[17 ms] connectionAcquired: Connection{localhost:52422, proxy=DIRECT hostAddress=localhost/127.0.0.1:52422 cipherSuite=none protocol=http/1.1}
FINE: Q1 scheduled after 300 s: OkHttp ConnectionPool
FINE: Q1 finished in 448 µs: OkHttp ConnectionPool
[20 ms] requestHeadersStart
[20 ms] requestHeadersEnd
[20 ms] requestBodyStart
[281 ms] requestBodyEnd: byteCount=6
[281 ms] responseHeadersStart
[543 ms] responseHeadersEnd: Response{protocol=http/1.1, code=200, message=OK, url=http://localhost:52422/}
[543 ms] responseBodyStart
[797 ms] responseBodyEnd: byteCount=65536
FINE: Q1 scheduled after 0 µs: OkHttp ConnectionPool
[797 ms] connectionReleased
[797 ms] callEnd
FINE: Q1 starting: OkHttp ConnectionPool
FINE: Q1 scheduled after 300 s: OkHttp ConnectionPool
FINE: Q1 finished in 178 µs: OkHttp ConnectionPool
```

**Comment by yschimke** [comment]
@swankjesse not sure how to read these?

```
FINE: Q5 scheduled after 300 s: OkHttp ConnectionPool cleanup
FINE: Q5 finished in 109 µs: OkHttp ConnectionPool cleanup
```

**Comment by yschimke** [comment]
WebSocketHttpTest.httpsScheme

```
Events (32)
FINE: Q2 scheduled after 0 µs: MockWebServer /127.0.0.1:59570
FINE: Q2 starting: MockWebServer /127.0.0.1:59570
FINE: Q1 scheduled after 0 µs: OkHttp ConnectionPool cleanup
FINE: Q1 starting: OkHttp ConnectionPool cleanup
FINE: Q1 scheduled after 300 s: OkHttp ConnectionPool cleanup
FINE: Q1 finished in 444 µs: OkHttp ConnectionPool cleanup
INFO: [WS server] onOpen
INFO: [WS client] onOpen
FINE: Q4 scheduled after 0 µs: OkHttp WebSocket https://localhost:59569/... writer
FINE: Q4 starting: OkHttp WebSocket https://localhost:59569/... writer
FINE: Q4 scheduled after 0 µs: OkHttp WebSocket https://localhost:59569/... writer
FINE: Q4 finished in 976 µs: OkHttp WebSocket https://localhost:59569/... writer
FINE: Q4 starting: OkHttp WebSocket https://localhost:59569/... writer
FINE: Q4 finished in 23 µs: OkHttp WebSocket https://localhost:59569/... writer
INFO: [WS server] onMessage
FINE: Q3 scheduled after 0 µs: MockWebServer WebSocket / writer
FINE: Q3 starting: MockWebServer WebSocket / writer
FINE: Q3 scheduled after 60 s: MockWebServer WebSocket / cancel
FINE: Q3 scheduled after 0 µs: MockWebServer WebSocket / writer
FINE: Q3 finished in 1 ms: MockWebServer WebSocket / writer
FINE: Q3 starting: MockWebServer WebSocket / writer
FINE: Q3 finished in 26 µs: MockWebServer WebSocket / writer
INFO: [WS client] onClosing 1001
FINE: Q4 scheduled after 0 µs: OkHttp WebSocket https://localhost:59569/... writer
FINE: Q4 starting: OkHttp WebSocket https://localhost:59569/... writer
INFO: [WS client] onClosed 1001
FINE: Q3 canceled: MockWebServer WebSocket / cancel
INFO: [WS server] onClosing 1000
INFO: [WS server] onClosed 1000
FINE: Q1 canceled: OkHttp ConnectionPool cleanup
FINE: Q4 finished in 3 ms: OkHttp WebSocket https://localhost:59569/... writer
FINE: Q2 finished in 297 ms: MockWebServer /127.0.0.1:59570
```

**Comment by yschimke** [comment]
Temporarily testing CallTest.tooManyProxyAuthFailuresWithConnectionClose

```
Events (110)
[0 ms] callStart: Request{method=GET, url=https://android.com/foo}
[0 ms] proxySelectStart: https://android.com/
[0 ms] proxySelectEnd: [HTTP @ localhost/127.0.0.1:60293]
[0 ms] dnsStart: 127.0.0.1
[0 ms] dnsEnd: [/127.0.0.1]
[0 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q2 scheduled after 0 µs: MockWebServer /127.0.0.1:60294
FINE: Q2 starting: MockWebServer /127.0.0.1:60294
[3 ms] connectEnd: null
[3 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q3 scheduled after 0 µs: MockWebServer /127.0.0.1:60295
FINE: Q2 finished in 3 ms: MockWebServer /127.0.0.1:60294
FINE: Q3 starting: MockWebServer /127.0.0.1:60295
[5 ms] connectEnd: null
[6 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q3 finished in 3 ms: MockWebServer /127.0.0.1:60295
FINE: Q4 scheduled after 0 µs: MockWebServer /127.0.0.1:60296
FINE: Q4 starting: MockWebServer /127.0.0.1:60296
[9 ms] connectEnd: null
[9 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q4 finished in 2 ms: MockWebServer /127.0.0.1:60296
FINE: Q5 scheduled after 0 µs: MockWebServer /127.0.0.1:60297
Dec 23, 2019 6:22:34 PM okhttp3.mockwebserver.MockWebServer$serveConnection$$inlined$execute$1 runOnce
SEVERE: MockWebServer[60293] connection from /127.0.0.1 crashed
java.lang.IllegalStateException: Tunnel without any CONNECT!
	at okhttp3.mockwebserver.MockWebServer$SocketHandler.createTunnel(MockWebServer.kt:572)
	at okhttp3.mockwebserver.MockWebServer$SocketHandler.handle(MockWebServer.kt:489)
FINE: Q5 starting: MockWebServer /127.0.0.1:60297
	at okhttp3.mockwebserver.MockWebServer$serveConnection$$inlined$execute$1.runOnce(TaskQueue.kt:200)
	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:115)
[12 ms] connectEnd: null
	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:41)
[12 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
FINE: Q5 finished in 3 ms: MockWebServer /127.0.0.1:60297
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
FINE: Q6 scheduled after 0 µs: MockWebServer /127.0.0.1:60298

FINE: Q6 starting: MockWebServer /127.0.0.1:60298
[14 ms] connectEnd: null
[14 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q6 finished in 1 ms: MockWebServer /127.0.0.1:60298
FINE: Q7 scheduled after 0 µs: MockWebServer /127.0.0.1:60299
FINE: Q7 starting: MockWebServer /127.0.0.1:60299
[16 ms] connectEnd: null
[16 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q7 finished in 1 ms: MockWebServer /127.0.0.1:60299
FINE: Q8 scheduled after 0 µs: MockWebServer /127.0.0.1:60300
FINE: Q8 starting: MockWebServer /127.0.0.1:60300
[17 ms] connectEnd: null
[17 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q8 finished in 2 ms: MockWebServer /127.0.0.1:60300
FINE: Q9 scheduled after 0 µs: MockWebServer /127.0.0.1:60301
FINE: Q9 starting: MockWebServer /127.0.0.1:60301
[19 ms] connectEnd: null
[19 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q9 finished in 2 ms: MockWebServer /127.0.0.1:60301
FINE: Q10 scheduled after 0 µs: MockWebServer /127.0.0.1:60302
FINE: Q10 starting: MockWebServer /127.0.0.1:60302
[21 ms] connectEnd: null
[21 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q10 finished in 2 ms: MockWebServer /127.0.0.1:60302
FINE: Q11 scheduled after 0 µs: MockWebServer /127.0.0.1:60303
FINE: Q11 starting: MockWebServer /127.0.0.1:60303
[23 ms] connectEnd: null
[23 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q11 finished in 3 ms: MockWebServer /127.0.0.1:60303
FINE: Q12 scheduled after 0 µs: MockWebServer /127.0.0.1:60304
FINE: Q12 starting: MockWebServer /127.0.0.1:60304
[25 ms] connectEnd: null
[25 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q12 finished in 1 ms: MockWebServer /127.0.0.1:60304
FINE: Q13 scheduled after 0 µs: MockWebServer /127.0.0.1:60305
FINE: Q13 starting: MockWebServer /127.0.0.1:60305
[28 ms] connectEnd: null
[28 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q13 finished in 3 ms: MockWebServer /127.0.0.1:60305
FINE: Q14 scheduled after 0 µs: MockWebServer /127.0.0.1:60306
FINE: Q14 starting: MockWebServer /127.0.0.1:60306
[30 ms] connectEnd: null
[30 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q14 finished in 1 ms: MockWebServer /127.0.0.1:60306
FINE: Q15 scheduled after 0 µs: MockWebServer /127.0.0.1:60307
FINE: Q15 starting: MockWebServer /127.0.0.1:60307
[32 ms] connectEnd: null
[32 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q15 finished in 1 ms: MockWebServer /127.0.0.1:60307
FINE: Q16 scheduled after 0 µs: MockWebServer /127.0.0.1:60308
FINE: Q16 starting: MockWebServer /127.0.0.1:60308
[33 ms] connectEnd: null
[33 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q16 finished in 2 ms: MockWebServer /127.0.0.1:60308
FINE: Q17 scheduled after 0 µs: MockWebServer /127.0.0.1:60309
FINE: Q17 starting: MockWebServer /127.0.0.1:60309
[36 ms] connectEnd: null
[36 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q17 finished in 3 ms: MockWebServer /127.0.0.1:60309
FINE: Q18 scheduled after 0 µs: MockWebServer /127.0.0.1:60310
FINE: Q18 starting: MockWebServer /127.0.0.1:60310
[38 ms] connectEnd: null
[38 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q18 finished in 1 ms: MockWebServer /127.0.0.1:60310
FINE: Q19 scheduled after 0 µs: MockWebServer /127.0.0.1:60311
FINE: Q19 starting: MockWebServer /127.0.0.1:60311
[39 ms] connectEnd: null
[39 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q19 finished in 1 ms: MockWebServer /127.0.0.1:60311
FINE: Q20 scheduled after 0 µs: MockWebServer /127.0.0.1:60312
FINE: Q20 starting: MockWebServer /127.0.0.1:60312
[40 ms] connectEnd: null
[40 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q21 scheduled after 0 µs: MockWebServer /127.0.0.1:60313
FINE: Q21 starting: MockWebServer /127.0.0.1:60313
FINE: Q20 finished in 2 ms: MockWebServer /127.0.0.1:60312
[42 ms] connectEnd: null
[43 ms] connectStart: /127.0.0.1:60293 HTTP @ localhost/127.0.0.1:60293
FINE: Q21 finished in 2 ms: MockWebServer /127.0.0.1:60313
FINE: Q22 scheduled after 0 µs: MockWebServer /127.0.0.1:60314
FINE: Q22 starting: MockWebServer /127.0.0.1:60314
[44 ms] connectEnd: null
[44 ms] callFailed: java.net.ProtocolException: Too many tunnel connections attempted: 21
Dec 23, 2019 6:22:34 PM okhttp3.mockwebserver.MockWebServer acceptConnections
INFO: MockWebServer[60293] done accepting connections: Socket closed
Dec 23, 2019 6:22:34 PM okhttp3.mockwebserver.MockWebServer acceptConnections
INFO: MockWebServer[60292] done accepting connections: Socket closed
```

**Comment by swankjesse** [comment]
@yschimke attempted to improve the logging here:
https://github.com/square/okhttp/pull/5671

**Pull request closed without merging**
