### PR TITLE
Windows test for #5761

### PR DESCRIPTION
**Pull request by bitwiseman**
@swankjesse  
I think this will reproduce #5761, however I don't run windows locally so it might not.

### CODE REVIEW

**Comment by bitwiseman** [comment]
Switch testjdk11 to windows.  There are a number failures (DiskLruCacheTest), but not my test which is in CacheTest.  😢

**Comment by swankjesse** [comment]
@bitwiseman does it fail locally on Windows?

**Comment by bitwiseman** [comment]
@swankjesse 
I don't have a local windows machine. I'm working blind. Sorry.  
Separate question, why isn't there already a Windows instance in the CI system?

**Comment by swankjesse** [comment]
We’ve never had a Windows-specific bug!

**Comment by bitwiseman** [comment]
@swankjesse  
Perhaps no one has ever filed one, but you have failing tests - see https://github.com/square/okhttp/pull/5769 .  😄

**Comment by bitwiseman** [comment]
Rebased this change on top of #5769.

**Comment by yschimke** [comment]
Hasn't moved since February, n.b. I have Windows tests running successfully, so if we re-open it should be with CI changes separately from any test changes.

**Comment by bitwiseman** [comment]
@yschimke  Yeah, I'm pretty sure this was superseded but other PRs including a fix.

**Pull request closed without merging**
