### PR TITLE
README: ProGuard changes for OkHttp 3.8.0

### PR DESCRIPTION
**Pull request by talklittle**

### CODE REVIEW

**Comment by swankjesse** [comment]
Brilliant, thank you. Wanna do Retrofit also?

**Comment by talklittle** [comment]
@swankjesse Thanks for the offer but I do not currently use Retrofit so it would be an untested config. I guess the place to document it would be https://github.com/square/retrofit/blob/master/website/index.html

**Comment by JakeWharton** [comment]
It's the same two additions.

**Comment by talklittle** [comment]
Go for it, I don't need to take credit for the PR on Retrofit.

**Pull request merged**
