### PR TITLE
Don't do health checks on brand new connections.

### PR DESCRIPTION
**Pull request by swankjesse**
This is imperfect, but it should save some unnecessary work and will
hopefully prevent RouteSelector from attempting a route when none is
available.

https://github.com/square/okhttp/issues/2151

### CODE REVIEW

**Comment by swankjesse** [comment]
Note that this is a PR for OkHttp 2.7. Once merged I’ll cut a 2.7.1.

**Comment by tankjj** [comment]
I found this patch may cause endless loop:
1. on a mobile phone, user sends one request, in function StreamAllocation::findHealthyConnection(), it returns a candidate
2. if this candidate successCount is 0, it is returned without health check.(candidate.isHealthy())
3. switch the phone's netowrk from 4G to wifi, so the socket is broken, the candidate is unhealthy.
4. to send request, SocketException(socket is closed) is thrown to RetryAndFollowUpInterceptor, and will have one more retry.
5.  StreamAllocation::findHealthyConnection() returns the same candidate.
...
so it causes endless loop.

**Comment by swankjesse** [comment]
Yikes. Can fix!

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/issues/5547

**Pull request merged**
