### PR TITLE
Fix OkHostnameVerifier cannot verify SSL certificate issued for IP address

### PR DESCRIPTION
**Pull request by topwu**
Fix OkHostnameVerifier cannot verify SSL certificate issued for IP address, a test is provided.

### CODE REVIEW

**Comment by swankjesse** [comment]
https://wiki.mozilla.org/CA:Problematic_Practices#Certificates_referencing_hostnames_or_private_IP_addresses

> “It is not standards compliant for printable ASCII representations of IP addresses to be placed in any certificate field that is intended to hold DNS names, including the subject common name and the DNSName field of the Subject Alternative Names extension. There is a place in a certificate specifically intended to be where IP (v4 or v6) addresses may be placed. It is in the Subject Alternative Names extension. The SubjectAltNames extension has places for both additional DNS names and for IP addresses. The place for IP addresses takes them in binary form, not in printable ASCII (e.g. dotted decimal) form.”

**Comment by swankjesse** [comment]
Sorry, this behavior is by design.

**Comment by topwu** [comment]
I though this is also fix the issue [#1467](https://github.com/square/okhttp/issues/1467#issuecomment-152850929)? 
Also [StrictHostnameVerifier](http://grepcode.com/file_/repo1.maven.org/maven2/com.ning/metrics.action/0.2.1/org/apache/http/conn/ssl/StrictHostnameVerifier.java/?v=source) in apache also support IP address.

**Comment by swankjesse** [comment]
It's probably an oversight on the bug. Maybe we can just close it. The subjectAltNames is the right place for IP addresses, not the CN. If Apache does it wrong, that's their bug.

**Pull request closed without merging**
