### PR TITLE
[WIP] Use key store from default SSLContext, if SSLSocketFactory is not set

### PR DESCRIPTION
**Pull request by tomfitzhenry**
Related: issue #1711.

### CODE REVIEW

**Comment by swankjesse** [comment]
Is this still a work in progress?

**Comment by tomfitzhenry** [comment]
Yes. It'll be finished when OkHttp uses the default KeyStore, or if that
isn't a desirable fix, the test will be changed to use the default
SSLSocketFactory, in which case the test will start passing.

Either way it'll be a test that documents the recommended way to do client
certificates in OkHttp.

There's some tidying to do too. I opened the PR, despite it being
incomplete, for early feedback and in case others found it useful. I can
remove it, if having a broken PR is inconvenient.

**Comment by swankjesse** [comment]
Could you turn this into a sample? We've got a samples directory where this would fit neatly.

Any way you can change your code to configure the keystore programmatically instead of with system properties? The problem with system properties is that they're global, which is unlikely to work in applications that make multiple kinds of HTTP requests.

**Comment by tomfitzhenry** [comment]
Thanks for prompt (modulo time zone) responses.

Yes, I can make it a sample instead of a test case. Why do you prefer it be
a sample, rather than a test, OOC?

With regards to programmatically configuring keystores, do you mean my
application code, or the code in the pull request?

If the former then the code that uses OkHttp is sonar-runner-api (used by
maven-sonar-plugin). Users expect to be able to pass client certificates
using the standard javax.net.ssl.keyStore system property, when executing
mvn.

Or do you mean the latter, and for example to add clientCertificate method
to OkHttp.Builder? I could. My concern with that is that other applications
that use OkHttp will not support client certificates (this tends to not be
considered by tool developers), making it hard for client certificate users.

What do you mean by "multiple kinds of HTTP requests"? I'll have a think
what I expect from a HTTP library API re client certificates, as if I had
multiple client certificates, and I wanted things like connection pooling
to work in some sane way. It's not immediately obvious what a good API for
that is.

**Comment by swankjesse** [comment]
> Why do you prefer it be a sample, rather than a test, OOC?

If the goal is documentation, samples feel less contrived. We expect end users to cut & paste samples into their projects. Samples can also hit webservers on the public Internet.


> With regards to programmatically configuring keystores, do you mean my application code, or the code in the pull request?

Yes, application code. I don’t think system properties are a good idea.


> Users expect to be able to pass client certificates using the standard javax.net.ssl.keyStore system property, when executing mvn.

If the Maven plugin supports this, then it should have its own configuration mechanism. Even just reading the supported system properties and configuring OkHttp with them should be sufficient.

**Comment by swankjesse** [comment]
Closing as stale. Happy to accept again if you’d like to resubmit without system properties!

**Pull request closed without merging**
