### PR TITLE
Conscrypt 1.3 with TLSv1.3

### PR DESCRIPTION
**Pull request by yschimke**
Testing of TLS 1.3 with Conscrypt

### CODE REVIEW

**Comment by yschimke** [comment]
```
Running tests using ConscryptPlatform 10.0.1+10
TLS1.3+TLS1.2
https://enabled.tls13.com                ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 140b
https://www.howsmyssl.com/a/check        ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 http/1.1 200 642b
https://tls13.cloudflare.com             ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 521 4546b
https://www.allizom.org/robots.txt       ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 119b
https://tls13.crypto.mozilla.org/        ConscryptPlatform
javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7fa4d947d448: Failure in SSL library, usually a protocol error
error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (../ssl/tls_record.cc:587 0x7fa4d94886e8:0x00000001)
https://tls.ctf.network/robots.txt       ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 http/1.1 404 169b
https://rustls.jbp.io/                   ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 http/1.1 200 416b
https://h2o.examp1e.net                  ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 h2 200 6209b
https://mew.org/                         ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 137b
https://tls13.baishancloud.com/          ConscryptPlatform
javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7fa4d9483b88: Failure in SSL library, usually a protocol error
error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (../ssl/tls_record.cc:587 0x7fa4d9483328:0x00000001)
error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (../ssl/handshake.cc:568 0x137166b9b:0x00000000)
https://tls13.akamai.io/                 ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 http/1.1 200 4732b
https://swifttls.org/                    ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 http/1.0 200 222b
https://www.googleapis.com/robots.txt    ConscryptPlatform
TLS_1_2 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 h2 200 25b
https://graph.facebook.com/robots.txt    ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 25b
https://api.twitter.com/robots.txt       ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 h2 200 155b
https://connect.squareup.com/robots.txt  ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 http/1.1 404 0b

TLS1.3 only
https://enabled.tls13.com                ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 140b
https://www.howsmyssl.com/a/check        ConscryptPlatform
javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7fa4d948c8d8: Failure in SSL library, usually a protocol error
error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (../ssl/tls_record.cc:587 0x7fa4d96ac278:0x00000001)
error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (../ssl/handshake.cc:568 0x137166b9b:0x00000000)
https://tls13.cloudflare.com             ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 521 4546b
https://www.allizom.org/robots.txt       ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 119b
https://tls13.crypto.mozilla.org/        ConscryptPlatform
javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7fa4db428658: Failure in SSL library, usually a protocol error
error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (../ssl/tls_record.cc:587 0x7fa4d9574698:0x00000001)
https://tls.ctf.network/robots.txt       ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 http/1.1 404 169b
https://rustls.jbp.io/                   ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 http/1.1 200 416b
https://h2o.examp1e.net                  ConscryptPlatform
javax.net.ssl.SSLHandshakeException
https://mew.org/                         ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 137b
https://tls13.baishancloud.com/          ConscryptPlatform
javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7fa4d96addf8: Failure in SSL library, usually a protocol error
error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (../ssl/tls_record.cc:587 0x7fa4d94650c8:0x00000001)
error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (../ssl/handshake.cc:568 0x137166b9b:0x00000000)
https://tls13.akamai.io/                 ConscryptPlatform
java.net.ConnectException: Failed to connect to tls13.akamai.io/2a02:26f0:5c:1a2:0:0:0:5f37:443
https://swifttls.org/                    ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 http/1.0 200 222b
https://www.googleapis.com/robots.txt    ConscryptPlatform
java.net.ConnectException: Failed to connect to www.googleapis.com/2a00:1450:4009:807:0:0:0:200a:443
https://graph.facebook.com/robots.txt    ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 25b
https://api.twitter.com/robots.txt       ConscryptPlatform
javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7fa4d96ba748: Failure in SSL library, usually a protocol error
error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (../ssl/tls_record.cc:587 0x7fa4d96bb5a8:0x00000001)
error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (../ssl/handshake.cc:568 0x137166b9b:0x00000000)
https://connect.squareup.com/robots.txt  ConscryptPlatform
javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7fa4d96ba7a8: Failure in SSL library, usually a protocol error
error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (../ssl/tls_record.cc:587 0x7fa4db427ce8:0x00000001)
error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (../ssl/handshake.cc:568 0x137166b9b:0x00000000)

TLS1.3 then fallback
https://enabled.tls13.com                ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 140b
https://www.howsmyssl.com/a/check        ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 http/1.1 200 581b
https://tls13.cloudflare.com             ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 521 4546b
https://www.allizom.org/robots.txt       ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 119b
https://tls13.crypto.mozilla.org/        ConscryptPlatform
javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7fa4d94b3c78: Failure in SSL library, usually a protocol error
error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (../ssl/tls_record.cc:587 0x7fa4d94b4d68:0x00000001)
https://tls.ctf.network/robots.txt       ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 http/1.1 404 169b
https://rustls.jbp.io/                   ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 http/1.1 200 416b
https://h2o.examp1e.net                  ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 h2 200 6209b
https://mew.org/                         ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 137b
https://tls13.baishancloud.com/          ConscryptPlatform
javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7fa4d966e518: Failure in SSL library, usually a protocol error
error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (../ssl/tls_record.cc:587 0x7fa4d958a588:0x00000001)
error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (../ssl/handshake.cc:568 0x137166b9b:0x00000000)
https://tls13.akamai.io/                 ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 http/1.1 200 4732b
https://swifttls.org/                    ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 http/1.0 200 222b
https://www.googleapis.com/robots.txt    ConscryptPlatform
TLS_1_2 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 h2 200 25b
https://graph.facebook.com/robots.txt    ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 25b
https://api.twitter.com/robots.txt       ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 h2 200 155b
https://connect.squareup.com/robots.txt  ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 http/1.1 404 0b
```

**Comment by yschimke** [comment]
cc @flooey

**Comment by yschimke** [comment]
```
Running tests using ConscryptPlatform 10.0.1+10
TLS1.3+TLS1.2
https://enabled.tls13.com                ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 140b
https://www.howsmyssl.com/a/check        ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 http/1.1 200 642b
https://tls13.cloudflare.com             ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 521 4546b
https://www.allizom.org/robots.txt       ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 119b
https://tls13.crypto.mozilla.org/        ConscryptPlatform
javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7fa84f7e5828: Failure in SSL library, usually a protocol error
error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (../ssl/tls_record.cc:587 0x7fa8510b6f18:0x00000001)
https://tls.ctf.network/robots.txt       ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 http/1.1 404 169b
https://rustls.jbp.io/                   ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 http/1.1 200 416b
https://h2o.examp1e.net                  ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 h2 200 6209b
https://mew.org/                         ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 137b
https://tls13.baishancloud.com/          ConscryptPlatform
javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7fa84f7e4e88: Failure in SSL library, usually a protocol error
error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (../ssl/tls_record.cc:587 0x7fa84f7e8218:0x00000001)
error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (../ssl/handshake.cc:568 0x12ac14b9b:0x00000000)
https://tls13.akamai.io/                 ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 http/1.1 200 4732b
https://swifttls.org/                    ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 http/1.0 200 222b
https://www.googleapis.com/robots.txt    ConscryptPlatform
TLS_1_2 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 h2 200 25b
https://graph.facebook.com/robots.txt    ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 25b
https://api.twitter.com/robots.txt       ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 h2 200 155b
https://connect.squareup.com/robots.txt  ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 http/1.1 404 0b

TLS1.3 only
https://enabled.tls13.com                ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 140b
https://www.howsmyssl.com/a/check        ConscryptPlatform
javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7fa84f770b88: Failure in SSL library, usually a protocol error
error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (../ssl/tls_record.cc:587 0x7fa84f7719a8:0x00000001)
error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (../ssl/handshake.cc:568 0x12ac14b9b:0x00000000)
https://tls13.cloudflare.com             ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 521 4546b
https://www.allizom.org/robots.txt       ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 119b
https://tls13.crypto.mozilla.org/        ConscryptPlatform
javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7fa84f778478: Failure in SSL library, usually a protocol error
error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (../ssl/tls_record.cc:587 0x7fa8511043e8:0x00000001)
https://tls.ctf.network/robots.txt       ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 http/1.1 404 169b
https://rustls.jbp.io/                   ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 http/1.1 200 416b
https://h2o.examp1e.net                  ConscryptPlatform
javax.net.ssl.SSLHandshakeException
https://mew.org/                         ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 137b
https://tls13.baishancloud.com/          ConscryptPlatform
javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7fa84f666038: Failure in SSL library, usually a protocol error
error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (../ssl/tls_record.cc:587 0x7fa84f770688:0x00000001)
error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (../ssl/handshake.cc:568 0x12ac14b9b:0x00000000)
https://tls13.akamai.io/                 ConscryptPlatform
java.net.ConnectException: Failed to connect to tls13.akamai.io/2a02:26f0:5c:1a2:0:0:0:5f37:443
https://swifttls.org/                    ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 http/1.0 200 222b
https://www.googleapis.com/robots.txt    ConscryptPlatform
java.net.ConnectException: Failed to connect to www.googleapis.com/2a00:1450:4009:80f:0:0:0:200a:443
https://graph.facebook.com/robots.txt    ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 25b
https://api.twitter.com/robots.txt       ConscryptPlatform
javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7fa84f4904f8: Failure in SSL library, usually a protocol error
error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (../ssl/tls_record.cc:587 0x7fa84f49a908:0x00000001)
error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (../ssl/handshake.cc:568 0x12ac14b9b:0x00000000)
https://connect.squareup.com/robots.txt  ConscryptPlatform
javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7fa84f699348: Failure in SSL library, usually a protocol error
error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (../ssl/tls_record.cc:587 0x7fa84f4904f8:0x00000001)
error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (../ssl/handshake.cc:568 0x12ac14b9b:0x00000000)

TLS1.3 then fallback
https://enabled.tls13.com                ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 140b
https://www.howsmyssl.com/a/check        ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 http/1.1 200 581b
https://tls13.cloudflare.com             ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 521 4546b
https://www.allizom.org/robots.txt       ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 119b
https://tls13.crypto.mozilla.org/        ConscryptPlatform
javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7fa84f49ea48: Failure in SSL library, usually a protocol error
error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (../ssl/tls_record.cc:587 0x7fa84f49fa38:0x00000001)
https://tls.ctf.network/robots.txt       ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 http/1.1 404 169b
https://rustls.jbp.io/                   ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 http/1.1 200 416b
https://h2o.examp1e.net                  ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 h2 200 6209b
https://mew.org/                         ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 137b
https://tls13.baishancloud.com/          ConscryptPlatform
javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7fa84f77c1b8: Failure in SSL library, usually a protocol error
error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (../ssl/tls_record.cc:587 0x7fa851456b58:0x00000001)
error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (../ssl/handshake.cc:568 0x12ac14b9b:0x00000000)
https://tls13.akamai.io/                 ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 http/1.1 200 4732b
https://swifttls.org/                    ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 http/1.0 200 222b
https://www.googleapis.com/robots.txt    ConscryptPlatform
TLS_1_2 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 h2 200 25b
https://graph.facebook.com/robots.txt    ConscryptPlatform
TLS_1_3 TLS_AES_128_GCM_SHA256 h2 200 25b
https://api.twitter.com/robots.txt       ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 h2 200 155b
https://connect.squareup.com/robots.txt  ConscryptPlatform
TLS_1_2 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 http/1.1 404 0b
```

**Comment by swankjesse** [comment]
Nice!

**Pull request merged**
