### PR TITLE
Add ';' to HttpUrl.QUERY_COMPONENT_ENCODE_SET

### PR DESCRIPTION
**Pull request by GUIpsp**
This fixes a real world issue found on GAE.

### CODE REVIEW

**Comment by GUIpsp** [comment]
Also, I think having different encoded sets for different parts of the URL is kinda silly, and we should just encode everything the [RFC](http://www.faqs.org/rfcs/rfc3986.html) says we should encode, but that's better left for another patch. This is just a quick fix.

**Comment by JakeWharton** [comment]
The HttpUrl class is not implemented to the URI RFC.

**Comment by swankjesse** [comment]
What's the bug?

**Comment by GUIpsp** [comment]
> The HttpUrl class is not implemented to the URI RFC.

Any reason why it shouldn't?

> What's the bug?

Try posting the equivalent of [this](http://pyeval.appspot.com/index.html) form with a script that contains `;` (say, `print ";"`). A browser will urlencode the `;` and it will work. OKHttp won't, and it will fail.

That form `post`s to `/exec` with `input` set to the python code which returns and id. You then need to `get` `/exec` with `id` set to the ID returned by the `post` to fetch the result of the evaluation.

**Comment by swankjesse** [comment]
Got it. This is about form encoding, which we're already planning on fixing.

**Comment by swankjesse** [comment]
Duplicate of
https://github.com/square/okhttp/issues/1694

**Comment by GUIpsp** [comment]
@swankjesse Neat, but this PR also fixes the issue, and I already signed the CLA.

**Comment by swankjesse** [comment]
Yeah, but this changes the behavior of URL canonicalization, which we don't want. We only want to change form encoding. If you'd like to submit a PR that does that, please do!

**Comment by GUIpsp** [comment]
Is the only char that needs to be added `;`?

**Comment by swankjesse** [comment]
@GUIpsp unsure. You could write a little program to see which characters Chrome and Firefox and Safari and IE escape in forms.

**Comment by GUIpsp** [comment]
From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent), `encodeURIComponent escapes all characters except the following: alphabetic, decimal digits, - _ . ! ~ * ' ( )`. This seems to match the [WHATWG's recommendations](https://html.spec.whatwg.org/multipage/forms.html#application/x-www-form-urlencoded-encoding-algorithm) `If the byte is in the range 0x2A, 0x2D, 0x2E, 0x30 to 0x39, 0x41 to 0x5A, 0x5F, 0x61 to 0x7A leave the byte as is.` `Otherwise encode`. However the current code present in okhttp uses a blacklist, not a whitelist. Is it worth it to implement a whitelist-like system for forms?

**Comment by swankjesse** [comment]
Yup, OkHttp 2.5.0's behavior is completely wrong, and it's my mistake!

I confirmed with Firefox & Chrome; both do percent-encoding of everything beyond 0x7f which isn't what we're doing.

https://gist.github.com/swankjesse/e46017775bb30f7e52c8

**Pull request closed without merging**
