### PR TITLE
Reset stream after a rollover

### PR DESCRIPTION
**Pull request by yschimke**

### CODE REVIEW

**Comment by yschimke** [comment]
Unclear how to effectively test, Tested manually via starting at Integer.MAX_VALUE - 4

Three successive requests, showing the 3rd silently retrying.

image

image

image

**Comment by yschimke** [comment]
relates to https://github.com/square/okhttp/issues/3670

**Comment by yschimke** [comment]
I'm suspecting this isn't a full fix, but as I think it will tear down the connection in RetryAndFollowUpInterceptor

**Comment by yschimke** [comment]
@swankjesse It seems better if StreamAllocation doesn't become aware of stream id logic.  Assuming this part stays in Http2Connection this seems exactly what shutdown is meant to achieve.

```
  /**
   * Degrades this connection such that new streams can neither be created locally, nor accepted
   * from the remote peer. Existing streams are not impacted. This is intended to permit an endpoint
   * to gracefully stop accepting new requests without harming previously established streams.
   */
  public void shutdown(ErrorCode statusCode) throws IOException {
```

**Comment by yschimke** [comment]
@swankjesse I put up an [updated diff](https://github.com/square/okhttp/pull/3752/commits/cdf3228ee3a4f7ab0c7d57a7cac19bcc45720bc3), but do you want it moved to Stream Allocation still? To me that is awkward because is put HTTP/2 logic in that shared class.

**Comment by swankjesse** [comment]
Yeah, I like this.

**Pull request merged**
