### PR TITLE
minor cleanup of EventListener formatting

### PR DESCRIPTION
**Pull request by yschimke**
Follow up from comments on reviews

### CODE REVIEW

**Comment by swankjesse** [comment]
[INFO] Starting audit...
LGTM but check style is even more pedantic than I am:
```
[ERROR] /home/travis/build/square/okhttp/okhttp/src/main/java/okhttp3/WebSocketListener.java:37: Line is longer than 100 characters (found 103). [LineLength]
```

**Comment by yschimke** [comment]
@swankjesse I didn't change that file?!?!

**Comment by swankjesse** [comment]
Ummm . . . superweird. Regardless, thanks for the cleanup.

**Comment by swankjesse** [comment]
Figured it out. I merged a PR earlier that was failing due to a flaky test. That PR also had a checkstyle violation. Now we’re all good.
https://github.com/square/okhttp/issues/3138

**Pull request merged**
