### PR TITLE
Prefer IPv4 over IPv6

### PR DESCRIPTION
**Pull request by thest1**
Prefer IPv4 over IPv6 because IPv4 has higher chances to be available. (see #1736)

### CODE REVIEW

**Comment by swankjesse** [comment]
This seems to contradict recent documentation claiming that IPv6 is faster.
https://code.facebook.com/posts/1192894270727351/ipv6-it-s-time-to-get-on-board-/

**Comment by thest1** [comment]
Thank you Jesse. Makes sense. So I'll have to make it just an option for those who have IPv6 problems.

**Comment by swankjesse** [comment]
@thest the other issue is that if you're suffering IPv6 issues, you should fix that in the network or in the OS, not in the application. It's a bad idea for every application to paper over lower-level bugs!

**Comment by thest1** [comment]
@swankjesse That's right. But most users can't handle that on their own. It's all about home wifi routers, user has no one to help there. They can see that all browsers work fine (due to Happy Eyeballs). So they can't imagine there's something wrong about their network. They're pretty sure my application is the one that's broken. Pretty sad. Anyway thank you for your feedback.

**Comment by warpspin** [comment]
Re-ordering the IP addresses by using Internal.instance.setNetwork to set a custom Network interface implementation is also what we have been doing for some time now, till Happy Eyeballs hopefully arrives one day in OkHttp. IPv4 in fact IS slower, depending on the ISP, especially on mobile, probably due to carrier grade NAT, but this is still preferable for now to 10 second delays per request on broken configurations. Our application still suffers from a bunch of 1 star reviews from users, usually with broken home networks.

**Comment by swankjesse** [comment]
Suppose we make the DNS lookup pluggable in 2.6. Then you don't need an internal API to get this behavior?

**Comment by warpspin** [comment]
At the moment, we're overriding resolveInetAddresses with a mechanism similar to @thest1's - in addition to re-ordering IP addresses for OkHttp, we also have hardcoded fallbacks for some host names, in case the resolving is completely bugged, so well, unless your pluggable DNS lookup is as powerful as the current Network-based mechanism, I'd probably still use internal APIs to achieve the result. If, by "pluggable DNS lookup" you basically mean promoting the current Network mechanism or something equally powerful to an official feature outside the internal.* package, I'm all for it, though.

```java
public class DnsClient implements Network {
    DnsClient() {}

    @Override
    public InetAddress[] resolveInetAddresses(final String host) throws UnknownHostException {
        return resolve(host, false );
    }

    private static InetAddress[] resolve(final String host, boolean preferIPv6) throws UnknownHostException {
        if (host == null) throw new UnknownHostException("host == null");
        InetAddress[] addresses;
        try {
            addresses = InetAddress.getAllByName(host);
        } catch( UnknownHostException e ) {
            addresses = fallbackResolver(host);
            if( addresses == null || addresses.length == 0 ) throw e;
        }
        if( addresses.length == 1 && host.endsWith(".spin.de") &&
                (addresses[0].isSiteLocalAddress() || addresses[0].isLinkLocalAddress())) {
            InetAddress[] tmpAddresses = fallbackResolver(host);
            if( tmpAddresses != null && tmpAddresses.length > 0 ) return tmpAddresses;
        }
        InetAddress[] result = new InetAddress[addresses.length];
        int i = 0;
        for( InetAddress addr : addresses ) {
            if( preferIPv6 ^ addr instanceof Inet4Address) {
                result[i++] = addr;
            }
        }
        for( InetAddress addr : addresses ) {
            if( !(preferIPv6 ^ addr instanceof Inet4Address)) {
                result[i++] = addr;
            }
        }
        return result;
    }

    // some more stuff, not only for okhttp...
}
```

**Comment by swankjesse** [comment]
@warpspin yep, this is about promoting the Network classes.

**Comment by thest1** [comment]
@warpspin Yeah, right now I do the same with Internal.instance.setNetwork(). Thanks for sharing your experience. Soon I'll see how it works for me in production.

**Comment by swankjesse** [comment]
As promised . . . https://github.com/square/okhttp/pull/1967

**Comment by swankjesse** [comment]
Closing this, I'm hoping the pluggable DNS API is sufficient!

**Pull request closed without merging**
