### PR TITLE
Use Date.from().

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
* Use the `Date.from(Instant)` method.

### CODE REVIEW

**Comment by yschimke** [comment]
Thanks, have you signed the CLA?

**Comment by Isira-Seneviratne** [comment]
> Thanks, have you signed the CLA?

No, I haven't. I'll do that, thanks.

**Comment by swankjesse** [comment]
Ugh, Date.from() needs API 26, and we support API 21+.
https://developer.android.com/reference/java/util/Date#from(java.time.Instant)

**Comment by swankjesse** [comment]
Oooh found this:
https://github.com/yschimke/okhttp/commit/47bca5f551ba21e0720ba3b6f66e0381306206ba

**Comment by Isira-Seneviratne** [comment]
> Ugh, Date.from() needs API 26, and we support API 21+.
> https://developer.android.com/reference/java/util/Date#from(java.time.Instant)

The whole of `java.time` (including Instant) requires API 26+, so the current implementation still gives those warnings. 

However, it's available via desugaring on earlier versions: https://developer.android.com/studio/write/java8-support-table

**Comment by Isira-Seneviratne** [comment]
> Ugh, Date.from() needs API 26, and we support API 21+.
> https://developer.android.com/reference/java/util/Date#from(java.time.Instant)

The method (and `java.time`) is backported for older versions by desugaring.

**Pull request merged**
