### PR TITLE
JDK 11 docker image for CircleCI

### PR DESCRIPTION
**Pull request by yschimke**
Trying to find a way around the error below

```
Mar 24, 2019 3:00:26 PM okhttp3.mockwebserver.MockWebServer$3 execute INFO: MockWebServer[45903] starting to accept connections Exception in thread "MockWebServer" j
java.lang.NoSuchMethodError: sun.security.ssl.SSLSessionImpl.<init>(Lsun/security/ssl/ProtocolVersion;Lsun/security/ssl/CipherSuite;Ljava/util/Collection;Ljava/security/SecureRandom;Ljava/lang/String;IZ)V 
  at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:787) a
```

Alternative option for CircleCI would be a custom docker image with Oracle JDK 8?

### CODE REVIEW

**Comment by yschimke** [comment]
Zoomed past the hanging tests

```
> Task :mockwebserver:test
> Task :okhttp-logging-interceptor:compileKotlin
> Task :okhttp-logging-interceptor:compileJava
```

**Comment by swankjesse** [comment]
Can we test both?

**Comment by yschimke** [comment]
Yep, but there isn't a matrix build IIUC, you just define a build pipeline with various jobs and reuse sections of the jobs.

**Comment by yschimke** [comment]
Think the other issue is predictably an ALPN issue

https://github.com/jetty-project/jetty-alpn/issues/22

**Comment by yschimke** [comment]
testing with branches, no PRs to avoid spam

**Pull request closed without merging**
