### PR TITLE
Clean Android Regression Test

### PR DESCRIPTION
**Pull request by yschimke**
Provides a clean test which is easily adaptable to reproduce failures on specific Android SDKs, devices or OkHttp versions (other than master).

### CODE REVIEW

**Comment by yschimke** [comment]
```
> Task :regression-test:connectedDebugAndroidTest
Starting 6 tests on test(AVD) - 10
```

**Comment by yschimke** [comment]
@swankjesse requesting post review, test only and will only run when a label is applied to a PR.

**Review by swankjesse — COMMENTED** [review]
I like it!

**Comment by swankjesse** [comment]
LGTM

**Pull request merged**
