### PR TITLE
Ignore minified files when searching code

### PR DESCRIPTION
**Pull request by grimreaper**

### CODE REVIEW

**Comment by JakeWharton** [comment]
What uses this file?

**Comment by grimreaper** [comment]
It's used by ag, ack, and a few other grep like tools. Usually you don't need to search minified files. I guess this might be considered global configuration.

**Comment by swankjesse** [comment]
Doesn't seem relevant to OkHttp.

**Comment by grimreaper** [comment]
closed;
FWIW I was using this to ignore
website/static/bootstrap.min.js
website/static/bootstrap-combined.min.css
but I just added them to my personal global config

**Pull request closed without merging**
