### PR TITLE
Updated gson recipe to close response body.

### PR DESCRIPTION
**Pull request by dave-r12**

### CODE REVIEW

**Comment by JakeWharton** [comment]
Hmm... we should really turn off animal sniffer for non-library modules. The use of try-with-resources is tripping up its enforcement of using Java 6 APIs only.

**Comment by dave-r12** [comment]
Oh, should I change it to just be a call to close() instead?

**Comment by JakeWharton** [comment]
Yeah. That would be easiest.

**Comment by swankjesse** [comment]
CLA is good! Thanks Dave.

**Pull request merged**
