### PR TITLE
Allow interrupt of singleton cleanup thread

### PR DESCRIPTION
**Pull request by yschimke**
If container aggressively interrupts the RealConnectionPool cleanup thread, then take notice to avoid waiting 60 seconds for daemon thread to cleanup normally.  However leave things in a sane state, so next connection established will restart it, and OkHttp will noisily log if this is done improperly without closing connections.

Related to https://github.com/square/okhttp/issues/3957 and Maven which violently interrupts daemon threads and noisily complains if they swallow interrupt exceptions.

TODO add tests if there is loose agreement this is correct logic.

### CODE REVIEW

**Comment by yschimke** [comment]
Not confident this will pass consensus, but Maven is a common enough container that we may want to allow for this usecase.  They are unlikely to change their thread handling for us.

**Comment by swankjesse** [comment]
Alright, lets be a little less container-hostile.

Can you change it to call `evictAll()` once interrupted? Something like this might work?

```
      while (true) {
        val waitNanos = cleanup(System.nanoTime())
        if (waitNanos == -1L) return
        try {
          this@RealConnectionPool.lockAndWaitNanos(waitNanos)
        } catch (_: InterruptedException) {
          // Will cause the thread to exit unless other connections are created!
          evictAll() 
        }
      }
```

**Comment by yschimke** [comment]
I'm a bit surprised you prefer this mode.  But it does keep the state in sync.  connections > 0 = cleanup running. It makes a weird API that interrupting a specific thread is a great way to cleanup all connections and threads forcefully.

**Comment by yschimke** [comment]
Looking into test failures

image

**Comment by swankjesse** [comment]
Only thing that’ll annoy container users is that our executor service will stick around for 60 seconds. Should we tighten this up to 1 second? 

(And perhaps we should use the same ExecutorService for this, HTTP/2’s readers, and HTTP/2’s callbacks.)

**Comment by yschimke** [comment]
@swankjesse I like that, I think we should aim for using signals like evicting the connection pool to stop background tasks nicely.  So doing the right thing appears to just work within 1 second as you say, I'll raise a tracking issue.

**Pull request merged**
