### PR TITLE
Use mapNotNull() extension.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
Use Kotlin's `mapNotNull` extension in `Cookie.parseAll()`.

### CODE REVIEW

**Comment by yschimke** [comment]
@swankjesse no objection from me.

But I seem to remember we avoided (early) kotlin loops because of allocations, is that a concern here? the current implementation seems allocation free for the no headers case which is the majority.

**Comment by JakeWharton** [comment]
The empty case will allocate an iterator, a backing mutable list, and an unmodifiable wrapper. Before it allocated nothing.

The non-empty case adds an additional iterator allocation to the previous code.

**Comment by yschimke** [comment]
Going to close this, while I don't have a strong objection, I'd be just as likely to accept the reverse as an optimisation.

**Comment by yschimke** [comment]
@Isira-Seneviratne could you raise an issue to discuss future changes before going ahead? I feel bad closing these and you having lost some time on them.

**Comment by Isira-Seneviratne** [comment]
> @Isira-Seneviratne could you raise an issue to discuss future changes before going ahead? I feel bad closing these and you having lost some time on them.

Sure.

**Pull request closed without merging**
