### PR TITLE
Use intrinsic version of toArray

### PR DESCRIPTION
**Pull request by yschimke**
Intellij advises to use this form post JVM 1.6 as it's an intrinsic that performs as well or better

### CODE REVIEW

**Comment by swankjesse** [comment]
Does Kotlin do it better?!

**Comment by yschimke** [comment]
Not sure, this is java -> java > 1.6

image

**Comment by JakeWharton** [comment]
FYI this comes from https://shipilev.net/blog/2016/arrays-wisdom-ancients/. I'll check ART later. It lacks an intrinsic for Arrays.copyOf and copyOfRange like the JVM so I was going to try to add it. Maybe we can get this added as well if it's missing.

**Comment by yschimke** [comment]
@JakeWharton do you want me to revert this change? or acceptable even if slower on ART for now?

**Comment by JakeWharton** [comment]
No. I don't think these are in hot paths where it should matter. Just want
to double check ART.

**Comment by JakeWharton** [comment]
Looks like Android doesn't do anything for either `toArray` variant so we'd probably need benchmarks to figure out which is better. But... who cares these aren't hotspots! Left as an exercise for someone else.

**Pull request merged**
