### PR TITLE
Setting default String locale to Locale.US

### PR DESCRIPTION
**Pull request by venilnoronha**
See #2522 for more info.

I've signed the CLA. Please review and pull.

Thanks,
Venil Noronha

### CODE REVIEW

**Comment by swankjesse** [comment]
Because it’s so noisy, could you create a helper method in Util called Util.format() that takes a String and an Object... ? 

Also, please squash to a single commit. See http://rebaseandsqua.sh for how.

**Comment by swankjesse** [comment]
And thank you much for this! Makes OkHttp better!

**Comment by venilnoronha** [comment]
Sure, I'll add the `Util.format(..)` method.

**Comment by venilnoronha** [comment]
Created `Util.format(String, Object...)` and squashed.

**Comment by venilnoronha** [comment]
@swankjesse Thanks!

**Pull request merged**
