### PR TITLE
Problem with ping interval

### PR DESCRIPTION
**Pull request by snjeza**
https://github.com/square/okhttp/issues/3297

### CODE REVIEW

**Comment by swankjesse** [comment]
I’d like to add a test before merging this.

**Comment by snjeza** [comment]
Would you like me to add it?

**Comment by yschimke** [comment]
Was trying to understand what a test looks like to progress this PR.  Something like the following? n.b. this assumes you move the check inside of writePingFrame() instead of in the Runnable

```
  @Test public void clientCloseThenWritingPingSucceeds() throws IOException {
    client.webSocket.close(1000, "Hello!");
    server.processNextFrame();
    server.listener.assertClosing(1000, "Hello!");

    client.webSocket.writePingFrame();
  }
```

**Comment by swankjesse** [comment]
Yep!

**Comment by aplut** [comment]
Hi,

do you have any update regarding this MR?

Cheers,
Adrian

**Pull request closed without merging**
