### PR TITLE
Some initial URL test cases.

### PR DESCRIPTION
**Pull request by swankjesse**
It turns out that even the spec that tries to describe how browsers actually
work doesn't completely accomplish that. So I'm trying to reconcile differences
between Firefox, Chrome and the WHATWG spec. In some cases I get three different
behaviors.

This adds tests for some interesting cases.

### CODE REVIEW

**Comment by swankjesse** [comment]
These webpages contain links that use strange links: the first contains a null character and the second contains a backspace character. I used 'em to confirm behavior in Firefox and Chrome.

https://publicobject.com/null.html
https://publicobject.com/backspace.html

**Comment by JakeWharton** [comment]
LGTM

**Comment by JakeWharton** [comment]
:shipit:

**Comment by swankjesse** [comment]
Working towards https://github.com/square/okhttp/issues/1486

**Pull request merged**
