### PR TITLE
Add additional headers and format response body to improve readability

### PR DESCRIPTION
**Pull request by StolarczykJakub**
This pull request added to the Interceptor a few changes:
- Formatting Json response body (without any extra dependency)
- Adding additional log headers 
- Selection of json indent spaces

All changes are disabled by default, we are still able to see standard type of logs.
I just wanted to improve UX for developers

### CODE REVIEW

**Comment by swankjesse** [comment]
We aren't taking new features in the logging interceptor. Its deliberately basic and we encourage you to use a fancier tool if you use it a lot. Some examples are Chucker for Android and Charles Proxy.

Please don't spend time wiritng PRs for OkHttp without getting a green light from project maintainers first. We would have been able to save you some time.

**Comment by swankjesse** [comment]
Also! This code looks reasonable enough. Please consider releasing it as a standalone project!

**Comment by yschimke** [comment]
+1 it would be great to see further innovation here and jitpack.io should make hosting your own library pretty low maintenance

**Comment by StolarczykJakub** [comment]
Thanks for feedback! My intention was to add it to the base so no extra libs needed. As android developer there is no application with networking without okhttp so it would be nice to be able to format those logs, but i understand and respect your decision. Take care :)

**Pull request closed without merging**
