### PR TITLE
Build a harness for web platform tests.

### PR DESCRIPTION
**Pull request by swankjesse**
This imports results from a few major browsers so we don't waste time
trying to pass tests that we shouldn't necessarily pass.

### CODE REVIEW

**Comment by JakeWharton** [comment]
The diff of this PR crashes mobile Chrome. Hah.

**Comment by JakeWharton** [comment]
LGTM. Looks like SPDY3 tests are flaking?

**Comment by swankjesse** [comment]
Yeah, flaky tests are (sadly) expected. @nfuller made things a bit more strict recently.

**Comment by swankjesse** [comment]
Working towards https://github.com/square/okhttp/issues/1486

**Pull request merged**
