### PR TITLE
Gracefully recover from an HTTP/2 connection shutdown at start of request.

### PR DESCRIPTION
**Pull request by dave-r12**
This was work started while addressing #2756, and is very much an edge case. I got sidetracked with the issue around violently and abruptly closing a socket and wanted to close the loop here.

### CODE REVIEW

**Comment by swankjesse** [comment]
Awesome. Thanks for closing the loop on this.

**Comment by kenyee** [comment]
Did this make it into 3.5?

**Comment by swankjesse** [comment]
@kenyee easiest way to find out is to check out the 3.5 tag and look for this commit.

**Comment by kenyee** [comment]
oops...was looking under branches (no branch for 3.5)...it's in 3.5 👍

**Pull request merged**
