### PR TITLE
Added documentation #2050

### PR DESCRIPTION
**Pull request by chaitanyajun12**
#2050 Added a one liner for the overriding of the Content-Length header.

### CODE REVIEW

**Comment by swankjesse** [comment]
Thanks! Please rebase and squash. http://rebaseandsqua.sh!

**Comment by chaitanyajun12** [comment]
Rebase and squashing done. Thanks.

**Comment by swankjesse** [comment]
Merged manually. Note that I tweaked your copy & formatting. In particular I dropped the word 'compression' because OkHttp doesn't do request compression out of the box, and your copy slightly suggests that. (We _do_ do response compression, so we have to be careful not to confuse our users!)

**Comment by chaitanyajun12** [comment]
Ok. Thanks for the correction.

**Pull request closed without merging**
