### PR TITLE
Add a test case  about  "Conform lockingSourceCount is correct" 

### PR DESCRIPTION
**Pull request by QingShiLuoGu**
just add a failing test case for #6363  so so you can fix it.

### CODE REVIEW

**Review by edith2727 — APPROVED** [review]

**Review by edith2727 — APPROVED** [review]
activar stripe

**Review by AFZAL4911 — COMMENTED** [review]
Hello dear
How is collect

**Comment by yschimke** [comment]
This should now be cleanly reproducible via Okio file system 

See https://github.com/square/okhttp/blob/ac63910c010af12686b7a86a07f401592dfc4fb9/okhttp/src/test/java/okhttp3/internal/cache/DiskLruCacheTest.kt#L51

Do you want to update the test and I'll take a look?

**Comment by QingShiLuoGu** [comment]
Do I need  fork the latest and then pull request agian?

**Comment by QingShiLuoGu** [comment]
hello, do I need fork the latest version and then pull request again?
Or can I just edit this commit?  @yschimke

**Comment by QingShiLuoGu** [comment]
I think it has been updated,please check it.  @yschimke

**Comment by yschimke** [comment]
@swankjesse any opinion on this test?

I'm assuming that DiskLruCache.Snapshot, which is closeable, should have a checkNotClosed() method, and fail fast if you try to use it after closing it.  But it breaks a bunch of other tests.  

image

**Comment by swankjesse** [comment]
@yschimke yeah that reads to me like a small bug? The snapshot should not be used after it is closed, though I think there's a valid use case to using a snapshot after it's enclosing cache is closed.

This class isn't public API so we can improve it's behavior where that’s useful. But we don't really need to be super aggressive about enforcing invariants unless we're worried we might inadvertently violate them.

**Comment by yschimke** [comment]
Going to close this one out unless we can reproduce with a test case using public API.  We can fix this, but it likely just incurs a tiny performance hit on each cache usage.

**Pull request closed without merging**
