### PR TITLE
fix authentication issue, 401 response code have never returns

### PR DESCRIPTION
**Pull request by busylee999**
https://github.com/square/okhttp/issues/1395

### CODE REVIEW

**Comment by swankjesse** [comment]
I don't think this works for applications that prompt for a password interactively. This is not backwards compatible.

**Comment by busylee999** [comment]
Yep, It seems not good. But I think it is bad never return 401 error. I faced this problem when I can not detect then user has bad credentials.

**Comment by swankjesse** [comment]
I think we need to surface the attempt number in the Response object.

**Comment by busylee999** [comment]
If we just pass number into response, it leads to excess attempts to connect using wrong credentials. I think it is better pass response with correct 401 error.

Consider we pass number of attempts. Where do you suppose user to handle it and do some thing?

**Pull request closed without merging**
