### PR TITLE
Test Pinning with cross signed certificates

### PR DESCRIPTION
**Pull request by yschimke**
> Mr. Schimke, what you've just coded is one of the most insanely idiotic things I have ever read. At no point in your rambling, incoherent test cases were you even close to anything that could be considered a rational thought. Everyone in this room is now dumber for having read it. I award you no points, and may God have mercy on your soul. 

As suspected, it's a real mess when there are multiple paths to a successful chain. I'm assuming someone stable, but awkward because you need to pin against both roots.

On Android we might also want to confirm that when connecting with 4 trusted certs we get the full chain, which appears to happen on the JDK.

### CODE REVIEW

**Comment by yschimke** [comment]
image

**Comment by yschimke** [comment]
Doesn't run by default but is high enough value as a check between now and January

**Comment by yschimke** [comment]
@swankjesse Want to land this and test under different providers? Or park/close unless we re-implement with MWS?

**Review by swankjesse — APPROVED** [review]
This makes my head hurt.

**Comment by yschimke** [comment]
@swankjesse It's probably better as a point in time PR. Will require updating the cert every 3 months, and the chain of trust is still in flux throughout January https://letsencrypt.org/certificates/

**Pull request closed without merging**
