### PR TITLE
Use double-checked singleton patterns.

### PR DESCRIPTION
**Pull request by HaoFeiWang**
The efficiency of Double-Check is higher.

### CODE REVIEW

**Comment by yschimke** [comment]
Is double checked locking safe in legacy Android phones?

Just curious: is this showing up in some profile as a hotspot?

**Comment by swankjesse** [comment]
I don’t like this. The performance benefits are negligible and the readability costs are real.

**Comment by artem-zinnatullin** [comment]
Hm, I like it tbh, only first call (realistically) needs synchronization, but current implementation synchronizes all the time. 

This PR will avoid synchronization in most of use-cases at cost of reading volatile which is not that bad.

But benchmark will be great.

**Comment by swankjesse** [comment]
This increases the amount of code to write, read, compile, download, and execute. It needs to be motivated by a real problem.

I'm closing this. If you can show how this fixes a performance problem, we can reconsider.

**Pull request closed without merging**
