### PR TITLE
Support the GMS security provider when searching for the trust manager.

### PR DESCRIPTION
**Pull request by swankjesse**
Closes https://github.com/square/okhttp/issues/2323

### CODE REVIEW

**Comment by vangliana** [comment]
It would be good if a release is made once this gets merged. This issue is wrecking havoc with any test relying on Robolectric runner

**Comment by JakeWharton** [comment]
@vangliana You can use the previous release, the SNAPSHOT from Sonatype's snapshot repository, or JitPack until a release is made.

**Comment by vangliana** [comment]
@JakeWharton previous release is no good since okhttp3.OkHttpClient modifier is final which breaks my mocks. I'll use the snapshot instead.

**Comment by JakeWharton** [comment]
Mocking `OkHttpClient` is an anti-pattern. You can mock or fake `Call.Factory` instead.

**Pull request merged**
