### PR TITLE
NEL Error Logging

### PR DESCRIPTION
**Pull request by yschimke**
A brief exploration of what NEL error logging could look like in OkHttp?

https://github.com/square/okhttp/issues/6413

### CODE REVIEW

**Comment by swankjesse** [comment]
I’m reluctant to introduce our own exception types that replace or wrap the built-in exception types. If we do it really well it’ll help users to debug their issues; but it also breaks all of our StackOverflow answers.

It’s also difficult to do fully because of where exceptions are thrown. Some are through Okio, some through JSSE/Conscrypt, and some through the JDK. Wrapping exceptions everywhere is going to be quite difficult to do well.

**Comment by yschimke** [comment]
@swankjesse any thoughts on suppressed exception as a carrier for the detail we want?

**Comment by swankjesse** [comment]
Backing up a bit – the ultimate goal is to improve metrics right? So operators can tell the difference between a TLS failure, a DNS failure, a timeout failure, etc.?

**Comment by yschimke** [comment]
> 
> 
> Backing up a bit – the ultimate goal is to improve metrics right? So operators can tell the difference between a TLS failure, a DNS failure, a timeout failure, etc.?

I'd say site operators (i provide some APIs across multiple platforms used by other developers and I'd like to know how and possibly why it's failing).  

Also as an app developer using OkHttp and Conscrypt (directly or through Android), I'd like to be able to self diagnore problems and report directly without asking for help in stackoverflow or OkHttp forums.

A wise man said

> But one thing we could do, which would be pretty nice, is to report our errors using the taxonomy here:
https://www.w3.org/TR/network-error-logging/#predefined-network-error-types

Hence moving this down into Conscrypt also https://github.com/google/conscrypt/issues/922

Also after the fact there is often more we could have done if details of the failure were accessible without assumptions of the implementation.  For example

```
  try {
    sslSocket.startHandshake()
  } catch (s: SSLHandshakeException) {
    val r = generateSequence<Throwable>(s) { it.cause }.find { it is CertPathValidatorException } as? CertPathValidatorException

    if (r != null) {
      println(r.certPath.certificates.map { (it as X509Certificate).subjectDN })
    }
  }
```

Can we as OkHttp pull this out and make it a clear error solution like certificate pinning failures?

**Pull request closed without merging**
