### PR TITLE
Remove creation of synthetic accessor methods.

### PR DESCRIPTION
**Pull request by vanniktech**
There are quite a few of them. Any of them were there by design?

### CODE REVIEW

**Comment by dave-r12** [comment]
Any before/after counts? Someone should create a maven plugin to catch these during build time.

**Comment by JakeWharton** [comment]
Last time I checked (about a year ago) OkHttp had something like 250
synthetic accessor methods.

**Comment by vanniktech** [comment]
IntelliJ inspections showed me I think 316 accessor methods.

**Comment by swankjesse** [comment]
Thanks.

**Pull request merged**
