### PR TITLE
Introduces MockWebServer builder API

### PR DESCRIPTION
**Pull request by bric3**
Hi,

This pull requests proposes a builder API for MockWebServer. The motivation is that the current API has a few limitations in comfort.

If used as a JUnit Rule, each mehtod has to configure the webserver in a repetitive way, while this is useful when testing different _communication_ setups, it can be a bit repetitive if the tests focus is the request/response exchange. Also when using MockWebServer as a JUnit rule it's impossible to configure the port binding. 

```java
@Rule
public MockWebServer server = new MockWebServer();

@Test
public void use_mock_web_server() {
  server.useHttps(serverHandshakeCertificates.sslSocketFactory());
  server.requestClientAuth();
  server.start(8443);
  // ...
}
```

After this PR

```java
@Rule
public MockWebServer server = new MockWebServer.Builder()
    .port(middleware.port())
    .useHttps(serverHandshakeCertificates.sslSocketFactory())
    .requestClientAuth()
    .build();

@Test
public void use_mock_weber_server_without_configuring() {
  // ...
}
```

For example before this PR, try-with-resources had to be used this way

```java
try(MockWebServer server = new MockWebServer())
  server.useHttps(serverHandshakeCertificates.sslSocketFactory());
  server.requestClientAuth();
  server.start(8443);
  // ...
}
```

After 

```java
try(MockWebServer server = new MockWebServer.Builder()
    .port(8443)
    .useHttps(serverHandshakeCertificates.sslSocketFactory())
    .requestClientAuth()
    .build()) {
  // ...
}
```

The proposed change don't break existing API however this lead some drawbacks I'm not quite happy with, e.g. this snippet is legal and won't raise any errors :

```java
MockWebServer server = new MockWebServer.Builder()
    .port(8443)
    .useHttps(serverHandshakeCertificates.sslSocketFactory())
    .requestClientAuth()
    .build()
server.noClientAuth();
server.start(8080);
```

I'm not sure how to address this. I'll be happy to fix any suggestions you have.
By the way I believe I have already signed the ICLA for leakcanary.

Cheers

### CODE REVIEW

**Comment by bric3** [comment]
This reminds me that this builder API could be used to introduce `ConnectionSpec` as in #4145 ?

**Comment by bric3** [comment]
Some stage of the build failed, but they don't seem related to the changes of this PR.

ci/circleci: testjdk8 failed with this test
 - okhttp3.WholeOperationTimeoutTest.noTimeout

Locally this comands succeeds `GRADLE_OPTS='-Dorg.gradle.daemon=false -Dokhttp.platform=jdk8 -Dorg.gradle.workers.max=3 -Xmx1G -Dtest.java.home=$HOME/.sdkman/candidates/java/8.0.232-amzn/' ./gradlew --build-cache --parallel --continue test`

ci/circleci: testjdk11 failed with these tests
 - okhttp3.InterceptorTest.interceptorMakesAnUnrelatedAsyncRequest
 - okhttp3.EventListenerTest.requestBodyFailHttp1OverHttps
 - okhttp3.EventListenerTest.requestBodyFailHttp2OverHttps
 - okhttp3.EventListenerTest.secureConnectWithTunnel
 - okhttp3.EventListenerTest.timeToFirstByteHttp1OverHttps
 - okhttp3.CacheTest.varyMatchesAddedRequestHeaderField

Locally this command `GRADLE_OPTS='-Dorg.gradle.daemon=false -Dokhttp.platform=jdk9 -Dorg.gradle.workers.max=3 -Xmx1G ' ./gradlew --build-cache --parallel --continue test` succeeds.

**Comment by swankjesse** [comment]
Neat! At this point I’m not interested in making incremental API improvements to MockWebServer because I don’t want to encourage our users to pay the cost to migrate.

BUT! I am interested in doing a real update to the MockWebServer APIs where we adopt modern API practices: immutable MockResponse objects, no JUnit dependency, streaming, etc.

**Comment by bric3** [comment]
> BUT! I am interested in doing a real update to the MockWebServer APIs where we adopt modern API practices: immutable MockResponse objects, no JUnit dependency, streaming, etc.

Does that mean deprecating MockWebServer in favor of another type/api ?

> Neat! At this point I’m not interested in making incremental API improvements to MockWebServer because I don’t want to encourage our users to pay the cost to migrate.

Fair enough, that's why I didn't want to deprectate the current API. The motivation was really to provide a way to configure the server at declaration before the server starts.

**Comment by swankjesse** [comment]
I’d prefer to avoid deprecating MockWebServer because I don’t want to cause downstream consumers to do the work to upgrade. The current thing works just fine; we just think we could do nicer.

But I do like the idea of introducing a new API, only if we could make it significantly better than what we have today. This is a big project!

For now I’d like to stall on this. I don’t want to make incremental API improvements when we should be making dramatic API improvements.

**Comment by bric3** [comment]
OK, thanks for explaining !
Is this something I could help with ? _I noticed a reference to OkHttpServer in #2916._

**Comment by yschimke** [comment]
I think we agreed to hold off on this for now.  Not a comment on the PR quality.

**Pull request closed without merging**
